package sei.tk.service.dao.mapper;

import org.apache.ibatis.annotations.Param;
import sei.tk.service.dao.model.TkKnopoint;
import sei.tk.service.dao.model.TkKnopointExample;

import java.util.List;

public interface TkKnopointMapper {

    List<TkKnopoint>   selectByCourse(String courseName);
    List<TkKnopoint> selectBycID(@Param("courseId") Short courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_knopoint
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int countByExample(TkKnopointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_knopoint
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int deleteByExample(TkKnopointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_knopoint
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int deleteByPrimaryKey(Long knopointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_knopoint
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int insert(TkKnopoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_knopoint
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int insertSelective(TkKnopoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_knopoint
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    List<TkKnopoint> selectByExample(TkKnopointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_knopoint
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    TkKnopoint selectByPrimaryKey(Long knopointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_knopoint
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") TkKnopoint record, @Param("example") TkKnopointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_knopoint
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByExample(@Param("record") TkKnopoint record, @Param("example") TkKnopointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_knopoint
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByPrimaryKeySelective(TkKnopoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_knopoint
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByPrimaryKey(TkKnopoint record);

}