package sei.tk.service.dao.mapper;

import org.apache.ibatis.annotations.Param;
import sei.tk.service.dao.model.TkStudypage;
import sei.tk.service.dao.model.TkStudypageExample;

import java.util.List;

public interface TkStudypageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_studypage
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int countByExample(TkStudypageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_studypage
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int deleteByExample(TkStudypageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_studypage
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int deleteByPrimaryKey(Long studypageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_studypage
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int insert(TkStudypage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_studypage
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int insertSelective(TkStudypage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_studypage
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    List<TkStudypage> selectByExample(TkStudypageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_studypage
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    TkStudypage selectByPrimaryKey(Long studypageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_studypage
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") TkStudypage record, @Param("example") TkStudypageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_studypage
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByExample(@Param("record") TkStudypage record, @Param("example") TkStudypageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_studypage
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByPrimaryKeySelective(TkStudypage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_studypage
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByPrimaryKey(TkStudypage record);
}