package sei.tk.service.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sei.tk.service.dao.model.TkStudent;
import sei.tk.service.dao.model.TkStudentExample;

public interface TkStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    int countByExample(TkStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    int deleteByExample(TkStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    int deleteByPrimaryKey(Long ppassportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    int insert(TkStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    int insertSelective(TkStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    List<TkStudent> selectByExample(TkStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    TkStudent selectByPrimaryKey(Long ppassportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    int updateByExampleSelective(@Param("record") TkStudent record, @Param("example") TkStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    int updateByExample(@Param("record") TkStudent record, @Param("example") TkStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    int updateByPrimaryKeySelective(TkStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    int updateByPrimaryKey(TkStudent record);
}