package sei.tk.service.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sei.tk.service.dao.model.*;
import sei.tk.service.dao.model.vo.robot.Question;
import sei.tk.service.dao.model.vo.robot.SubNum;

public interface TkSubjectMapper {

    /**
     *
     * @param courseId
     * @param knopointId
     * @param levelId
     * @param quetypeId
     * @return
     */
    List<TkSubjectWithBLOBs> selectByKnpoint(@Param("course_id")Short courseId,@Param("chapter_id") Byte chapterId ,@Param("knopoint_id")Long knopointId,@Param("level_id")Byte levelId,@Param("quetype_id")Short quetypeId);




    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Mon Mar 14 22:39:55 CST 2016
     */
    int countByExample(TkSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Mon Mar 14 22:39:55 CST 2016
     */
    int deleteByExample(TkSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Mon Mar 14 22:39:55 CST 2016
     */
    int deleteByPrimaryKey(Long subjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Mon Mar 14 22:39:55 CST 2016
     */
    int insert(TkSubjectWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Mon Mar 14 22:39:55 CST 2016
     */
    int insertSelective(TkSubjectWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Mon Mar 14 22:39:55 CST 2016
     */
    List<TkSubjectWithBLOBs> selectByExampleWithBLOBs(TkSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Mon Mar 14 22:39:55 CST 2016
     */
    List<TkSubject> selectByExample(TkSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Mon Mar 14 22:39:55 CST 2016
     */
    TkSubjectWithBLOBs selectByPrimaryKey(Long subjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Mon Mar 14 22:39:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") TkSubjectWithBLOBs record, @Param("example") TkSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Mon Mar 14 22:39:55 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") TkSubjectWithBLOBs record, @Param("example") TkSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Mon Mar 14 22:39:55 CST 2016
     */
    int updateByExample(@Param("record") TkSubject record, @Param("example") TkSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Mon Mar 14 22:39:55 CST 2016
     */
    int updateByPrimaryKeySelective(TkSubjectWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Mon Mar 14 22:39:55 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TkSubjectWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Mon Mar 14 22:39:55 CST 2016
     */
    int updateByPrimaryKey(TkSubject record);

    /**
     *
     * 得到随机出来的题
     **/
    List<TkSubject>  selectRandSubject(Question question);

    /**
     *
     * 通过课程id,题型id，知识点id 得到该题型该知识点每种难度的题目数
     *
     * **/
     List<SubNum>  selectandGetNum( TkSubject tkSubject);

    /**
     * 将课程排序
     * @param tkSubjectExample
     * @return
     */
    List<TkSubjectWithBLOBs> selectSubOrderBy(TkSubjectExample tkSubjectExample);
    List<Integer> selectChapterGroup(Short courseId);

}