package sei.tk.service.dao.mapper;

import org.apache.ibatis.annotations.Param;
import sei.tk.service.dao.model.TkTest;
import sei.tk.service.dao.model.TkTestExample;

import java.util.List;

public interface TkTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_test
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int countByExample(TkTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_test
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int deleteByExample(TkTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_test
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int deleteByPrimaryKey(Long testUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_test
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int insert(TkTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_test
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int insertSelective(TkTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_test
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    List<TkTest> selectByExample(TkTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_test
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    TkTest selectByPrimaryKey(Long testUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_test
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") TkTest record, @Param("example") TkTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_test
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByExample(@Param("record") TkTest record, @Param("example") TkTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_test
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByPrimaryKeySelective(TkTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_test
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByPrimaryKey(TkTest record);
}