package sei.tk.service.dao.mapper;

import org.apache.ibatis.annotations.Param;
import sei.tk.service.dao.model.TkTestsubject;
import sei.tk.service.dao.model.TkTestsubjectExample;

import java.util.List;

public interface TkTestsubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testsubject
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int countByExample(TkTestsubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testsubject
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int deleteByExample(TkTestsubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testsubject
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int deleteByPrimaryKey(Long testpaperUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testsubject
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int insert(TkTestsubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testsubject
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int insertSelective(TkTestsubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testsubject
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    List<TkTestsubject> selectByExample(TkTestsubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testsubject
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    TkTestsubject selectByPrimaryKey(Long testpaperUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testsubject
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") TkTestsubject record, @Param("example") TkTestsubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testsubject
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByExample(@Param("record") TkTestsubject record, @Param("example") TkTestsubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testsubject
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByPrimaryKeySelective(TkTestsubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testsubject
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByPrimaryKey(TkTestsubject record);
    /**
     * 查找所有的subjectId
     * @return
     */
    List<TkTestsubject> selectAllSubjectId(Long testpaperId);
    int deletebytestpaperid (Long testpaperId);
}