package sei.tk.service.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sei.tk.service.dao.model.TkTeacher;
import sei.tk.service.dao.model.TkTeacherExample;

public interface TkTeacherMapper {

    String getTeanamebyPassportId(Long passportId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    int countByExample(TkTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    int deleteByExample(TkTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    int deleteByPrimaryKey(String teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    int insert(TkTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    int insertSelective(TkTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    List<TkTeacher> selectByExample(TkTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    TkTeacher selectByPrimaryKey(String teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") TkTeacher record, @Param("example") TkTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    int updateByExample(@Param("record") TkTeacher record, @Param("example") TkTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    int updateByPrimaryKeySelective(TkTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    int updateByPrimaryKey(TkTeacher record);
}