package sei.tk.service.dao.mapper;

import org.apache.ibatis.annotations.Param;
import sei.tk.service.dao.model.TkTestpaper;
import sei.tk.service.dao.model.TkTestpaperExample;
import sei.tk.service.dao.model.vo.paper.PaperInfo;

import java.util.List;

public interface TkTestpaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testpaper
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int countByExample(TkTestpaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testpaper
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int deleteByExample(TkTestpaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testpaper
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int deleteByPrimaryKey(Long testpaperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testpaper
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int insert(TkTestpaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testpaper
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int insertSelective(TkTestpaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testpaper
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    List<TkTestpaper> selectByExample(TkTestpaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testpaper
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    TkTestpaper selectByPrimaryKey(Long testpaperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testpaper
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") TkTestpaper record, @Param("example") TkTestpaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testpaper
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByExample(@Param("record") TkTestpaper record, @Param("example") TkTestpaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testpaper
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByPrimaryKeySelective(TkTestpaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testpaper
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByPrimaryKey(TkTestpaper record);
    /**
     * 找出最大的testpaperId
     * @return
     */
    Long selectMaxTestpaperId();

    /**
     * 显示所有testpaperId
     * @return
     */
    List<TkTestpaper> selectAllTestpaperId();

    /**
     *
     * 得到最新添加的id
     */
    long selectlastinsertid() ;
    /**
     * 通过Testpaperid 得到 mkpaperid
     *
     */
    long selectMkpaperid(Long testpaperId);
}