package sei.tk.service.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sei.tk.service.dao.model.TkTestschedule;
import sei.tk.service.dao.model.TkTestscheduleExample;
import sei.tk.service.dao.model.vo.testSchedule.TeaGetAllSch;
import sei.tk.service.dao.model.vo.testSchedule.TeaGetSchId;

public interface TkTestscheduleMapper {
    List<TkTestschedule> getAllExamInfo(TeaGetAllSch teaGetAllSch); //查询当前老师的安排
    List<TkTestschedule> getAllSchId(TeaGetSchId teaGetSchId);   //根据时间、试卷号查询所有被安排的学生的安排号

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testschedule
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    int countByExample(TkTestscheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testschedule
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    int deleteByExample(TkTestscheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testschedule
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    int deleteByPrimaryKey(Long testscheduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testschedule
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    int insert(TkTestschedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testschedule
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    int insertSelective(TkTestschedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testschedule
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    List<TkTestschedule> selectByExample(TkTestscheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testschedule
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    TkTestschedule selectByPrimaryKey(Long testscheduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testschedule
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") TkTestschedule record, @Param("example") TkTestscheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testschedule
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    int updateByExample(@Param("record") TkTestschedule record, @Param("example") TkTestscheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testschedule
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    int updateByPrimaryKeySelective(TkTestschedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testschedule
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    int updateByPrimaryKey(TkTestschedule record);
}