package sei.tk.service.dao.mapper;

import org.apache.ibatis.annotations.Param;
import sei.tk.service.dao.model.TkTestanswer;
import sei.tk.service.dao.model.TkTestanswerExample;

import java.util.List;

public interface TkTestanswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testanswer
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int countByExample(TkTestanswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testanswer
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int deleteByExample(TkTestanswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testanswer
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int deleteByPrimaryKey(Long testpaperanswerUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testanswer
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int insert(TkTestanswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testanswer
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int insertSelective(TkTestanswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testanswer
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    List<TkTestanswer> selectByExampleWithBLOBs(TkTestanswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testanswer
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    List<TkTestanswer> selectByExample(TkTestanswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testanswer
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    TkTestanswer selectByPrimaryKey(Long testpaperanswerUuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testanswer
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") TkTestanswer record, @Param("example") TkTestanswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testanswer
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") TkTestanswer record, @Param("example") TkTestanswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testanswer
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByExample(@Param("record") TkTestanswer record, @Param("example") TkTestanswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testanswer
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByPrimaryKeySelective(TkTestanswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testanswer
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TkTestanswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_testanswer
     *
     * @mbggenerated Wed Mar 23 08:59:41 CST 2016
     */
    int updateByPrimaryKey(TkTestanswer record);
//批量插入
    int insertBatchSelective(List<TkTestanswer> tkTestanswers);
}