package sei.tk.service.dao.model;

public class TkCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_course.course_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Short courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_course.course_name
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private String courseName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_course.course_id
     *
     * @return the value of tk_course.course_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Short getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_course.course_id
     *
     * @param courseId the value for tk_course.course_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setCourseId(Short courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_course.course_name
     *
     * @return the value of tk_course.course_name
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_course.course_name
     *
     * @param courseName the value for tk_course.course_name
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }
}