package sei.tk.service.dao.model;

import java.util.ArrayList;
import java.util.List;

public class TkMkpaperruleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated Sat Apr 09 17:02:39 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated Sat Apr 09 17:02:39 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated Sat Apr 09 17:02:39 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated Sat Apr 09 17:02:39 CST 2016
     */
    public TkMkpaperruleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated Sat Apr 09 17:02:39 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated Sat Apr 09 17:02:39 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated Sat Apr 09 17:02:39 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated Sat Apr 09 17:02:39 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated Sat Apr 09 17:02:39 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated Sat Apr 09 17:02:39 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated Sat Apr 09 17:02:39 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated Sat Apr 09 17:02:39 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated Sat Apr 09 17:02:39 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated Sat Apr 09 17:02:39 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated Sat Apr 09 17:02:39 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMkpaperruleIdIsNull() {
            addCriterion("mkpaperrule_id is null");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleIdIsNotNull() {
            addCriterion("mkpaperrule_id is not null");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleIdEqualTo(Long value) {
            addCriterion("mkpaperrule_id =", value, "mkpaperruleId");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleIdNotEqualTo(Long value) {
            addCriterion("mkpaperrule_id <>", value, "mkpaperruleId");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleIdGreaterThan(Long value) {
            addCriterion("mkpaperrule_id >", value, "mkpaperruleId");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("mkpaperrule_id >=", value, "mkpaperruleId");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleIdLessThan(Long value) {
            addCriterion("mkpaperrule_id <", value, "mkpaperruleId");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleIdLessThanOrEqualTo(Long value) {
            addCriterion("mkpaperrule_id <=", value, "mkpaperruleId");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleIdIn(List<Long> values) {
            addCriterion("mkpaperrule_id in", values, "mkpaperruleId");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleIdNotIn(List<Long> values) {
            addCriterion("mkpaperrule_id not in", values, "mkpaperruleId");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleIdBetween(Long value1, Long value2) {
            addCriterion("mkpaperrule_id between", value1, value2, "mkpaperruleId");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleIdNotBetween(Long value1, Long value2) {
            addCriterion("mkpaperrule_id not between", value1, value2, "mkpaperruleId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdIsNull() {
            addCriterion("mkpaper_id is null");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdIsNotNull() {
            addCriterion("mkpaper_id is not null");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdEqualTo(Long value) {
            addCriterion("mkpaper_id =", value, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdNotEqualTo(Long value) {
            addCriterion("mkpaper_id <>", value, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdGreaterThan(Long value) {
            addCriterion("mkpaper_id >", value, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdGreaterThanOrEqualTo(Long value) {
            addCriterion("mkpaper_id >=", value, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdLessThan(Long value) {
            addCriterion("mkpaper_id <", value, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdLessThanOrEqualTo(Long value) {
            addCriterion("mkpaper_id <=", value, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdIn(List<Long> values) {
            addCriterion("mkpaper_id in", values, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdNotIn(List<Long> values) {
            addCriterion("mkpaper_id not in", values, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdBetween(Long value1, Long value2) {
            addCriterion("mkpaper_id between", value1, value2, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdNotBetween(Long value1, Long value2) {
            addCriterion("mkpaper_id not between", value1, value2, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdIsNull() {
            addCriterion("quetype_id is null");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdIsNotNull() {
            addCriterion("quetype_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdEqualTo(Short value) {
            addCriterion("quetype_id =", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdNotEqualTo(Short value) {
            addCriterion("quetype_id <>", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdGreaterThan(Short value) {
            addCriterion("quetype_id >", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdGreaterThanOrEqualTo(Short value) {
            addCriterion("quetype_id >=", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdLessThan(Short value) {
            addCriterion("quetype_id <", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdLessThanOrEqualTo(Short value) {
            addCriterion("quetype_id <=", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdIn(List<Short> values) {
            addCriterion("quetype_id in", values, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdNotIn(List<Short> values) {
            addCriterion("quetype_id not in", values, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdBetween(Short value1, Short value2) {
            addCriterion("quetype_id between", value1, value2, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdNotBetween(Short value1, Short value2) {
            addCriterion("quetype_id not between", value1, value2, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdIsNull() {
            addCriterion("knopoint_id is null");
            return (Criteria) this;
        }

        public Criteria andKnopointIdIsNotNull() {
            addCriterion("knopoint_id is not null");
            return (Criteria) this;
        }

        public Criteria andKnopointIdEqualTo(String value) {
            addCriterion("knopoint_id =", value, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdNotEqualTo(String value) {
            addCriterion("knopoint_id <>", value, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdGreaterThan(String value) {
            addCriterion("knopoint_id >", value, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdGreaterThanOrEqualTo(String value) {
            addCriterion("knopoint_id >=", value, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdLessThan(String value) {
            addCriterion("knopoint_id <", value, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdLessThanOrEqualTo(String value) {
            addCriterion("knopoint_id <=", value, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdLike(String value) {
            addCriterion("knopoint_id like", value, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdNotLike(String value) {
            addCriterion("knopoint_id not like", value, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdIn(List<String> values) {
            addCriterion("knopoint_id in", values, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdNotIn(List<String> values) {
            addCriterion("knopoint_id not in", values, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdBetween(String value1, String value2) {
            addCriterion("knopoint_id between", value1, value2, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdNotBetween(String value1, String value2) {
            addCriterion("knopoint_id not between", value1, value2, "knopointId");
            return (Criteria) this;
        }

        public Criteria andLevelIdIsNull() {
            addCriterion("level_id is null");
            return (Criteria) this;
        }

        public Criteria andLevelIdIsNotNull() {
            addCriterion("level_id is not null");
            return (Criteria) this;
        }

        public Criteria andLevelIdEqualTo(Byte value) {
            addCriterion("level_id =", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdNotEqualTo(Byte value) {
            addCriterion("level_id <>", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdGreaterThan(Byte value) {
            addCriterion("level_id >", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdGreaterThanOrEqualTo(Byte value) {
            addCriterion("level_id >=", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdLessThan(Byte value) {
            addCriterion("level_id <", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdLessThanOrEqualTo(Byte value) {
            addCriterion("level_id <=", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdIn(List<Byte> values) {
            addCriterion("level_id in", values, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdNotIn(List<Byte> values) {
            addCriterion("level_id not in", values, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdBetween(Byte value1, Byte value2) {
            addCriterion("level_id between", value1, value2, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdNotBetween(Byte value1, Byte value2) {
            addCriterion("level_id not between", value1, value2, "levelId");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleScoreIsNull() {
            addCriterion("mkpaperrule_score is null");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleScoreIsNotNull() {
            addCriterion("mkpaperrule_score is not null");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleScoreEqualTo(Short value) {
            addCriterion("mkpaperrule_score =", value, "mkpaperruleScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleScoreNotEqualTo(Short value) {
            addCriterion("mkpaperrule_score <>", value, "mkpaperruleScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleScoreGreaterThan(Short value) {
            addCriterion("mkpaperrule_score >", value, "mkpaperruleScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleScoreGreaterThanOrEqualTo(Short value) {
            addCriterion("mkpaperrule_score >=", value, "mkpaperruleScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleScoreLessThan(Short value) {
            addCriterion("mkpaperrule_score <", value, "mkpaperruleScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleScoreLessThanOrEqualTo(Short value) {
            addCriterion("mkpaperrule_score <=", value, "mkpaperruleScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleScoreIn(List<Short> values) {
            addCriterion("mkpaperrule_score in", values, "mkpaperruleScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleScoreNotIn(List<Short> values) {
            addCriterion("mkpaperrule_score not in", values, "mkpaperruleScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleScoreBetween(Short value1, Short value2) {
            addCriterion("mkpaperrule_score between", value1, value2, "mkpaperruleScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleScoreNotBetween(Short value1, Short value2) {
            addCriterion("mkpaperrule_score not between", value1, value2, "mkpaperruleScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleAmountIsNull() {
            addCriterion("mkpaperrule_amount is null");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleAmountIsNotNull() {
            addCriterion("mkpaperrule_amount is not null");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleAmountEqualTo(Short value) {
            addCriterion("mkpaperrule_amount =", value, "mkpaperruleAmount");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleAmountNotEqualTo(Short value) {
            addCriterion("mkpaperrule_amount <>", value, "mkpaperruleAmount");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleAmountGreaterThan(Short value) {
            addCriterion("mkpaperrule_amount >", value, "mkpaperruleAmount");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleAmountGreaterThanOrEqualTo(Short value) {
            addCriterion("mkpaperrule_amount >=", value, "mkpaperruleAmount");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleAmountLessThan(Short value) {
            addCriterion("mkpaperrule_amount <", value, "mkpaperruleAmount");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleAmountLessThanOrEqualTo(Short value) {
            addCriterion("mkpaperrule_amount <=", value, "mkpaperruleAmount");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleAmountIn(List<Short> values) {
            addCriterion("mkpaperrule_amount in", values, "mkpaperruleAmount");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleAmountNotIn(List<Short> values) {
            addCriterion("mkpaperrule_amount not in", values, "mkpaperruleAmount");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleAmountBetween(Short value1, Short value2) {
            addCriterion("mkpaperrule_amount between", value1, value2, "mkpaperruleAmount");
            return (Criteria) this;
        }

        public Criteria andMkpaperruleAmountNotBetween(Short value1, Short value2) {
            addCriterion("mkpaperrule_amount not between", value1, value2, "mkpaperruleAmount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 09 17:02:39 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_mkpaperrule
     *
     * @mbggenerated Sat Apr 09 17:02:39 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}