package sei.tk.service.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TkMkpaperExample {
    protected Integer start;    //∑÷“≥œ‡πÿ
    protected Integer row;

    public Integer getStart() {
        return start;
    }

    public void setStart(Integer start) {
        this.start = start;
    }

    public Integer getRow() {
        return row;
    }

    public void setRow(Integer row) {
        this.row = row;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_mkpaper
     *
     * @mbggenerated Tue Apr 12 20:45:29 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_mkpaper
     *
     * @mbggenerated Tue Apr 12 20:45:29 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_mkpaper
     *
     * @mbggenerated Tue Apr 12 20:45:29 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaper
     *
     * @mbggenerated Tue Apr 12 20:45:29 CST 2016
     */
    public TkMkpaperExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaper
     *
     * @mbggenerated Tue Apr 12 20:45:29 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaper
     *
     * @mbggenerated Tue Apr 12 20:45:29 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaper
     *
     * @mbggenerated Tue Apr 12 20:45:29 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaper
     *
     * @mbggenerated Tue Apr 12 20:45:29 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaper
     *
     * @mbggenerated Tue Apr 12 20:45:29 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaper
     *
     * @mbggenerated Tue Apr 12 20:45:29 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaper
     *
     * @mbggenerated Tue Apr 12 20:45:29 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaper
     *
     * @mbggenerated Tue Apr 12 20:45:29 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaper
     *
     * @mbggenerated Tue Apr 12 20:45:29 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_mkpaper
     *
     * @mbggenerated Tue Apr 12 20:45:29 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_mkpaper
     *
     * @mbggenerated Tue Apr 12 20:45:29 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMkpaperIdIsNull() {
            addCriterion("mkpaper_id is null");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdIsNotNull() {
            addCriterion("mkpaper_id is not null");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdEqualTo(Long value) {
            addCriterion("mkpaper_id =", value, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdNotEqualTo(Long value) {
            addCriterion("mkpaper_id <>", value, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdGreaterThan(Long value) {
            addCriterion("mkpaper_id >", value, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdGreaterThanOrEqualTo(Long value) {
            addCriterion("mkpaper_id >=", value, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdLessThan(Long value) {
            addCriterion("mkpaper_id <", value, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdLessThanOrEqualTo(Long value) {
            addCriterion("mkpaper_id <=", value, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdIn(List<Long> values) {
            addCriterion("mkpaper_id in", values, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdNotIn(List<Long> values) {
            addCriterion("mkpaper_id not in", values, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdBetween(Long value1, Long value2) {
            addCriterion("mkpaper_id between", value1, value2, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andMkpaperIdNotBetween(Long value1, Long value2) {
            addCriterion("mkpaper_id not between", value1, value2, "mkpaperId");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNull() {
            addCriterion("course_id is null");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNotNull() {
            addCriterion("course_id is not null");
            return (Criteria) this;
        }

        public Criteria andCourseIdEqualTo(Short value) {
            addCriterion("course_id =", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotEqualTo(Short value) {
            addCriterion("course_id <>", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThan(Short value) {
            addCriterion("course_id >", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThanOrEqualTo(Short value) {
            addCriterion("course_id >=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThan(Short value) {
            addCriterion("course_id <", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThanOrEqualTo(Short value) {
            addCriterion("course_id <=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdIn(List<Short> values) {
            addCriterion("course_id in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotIn(List<Short> values) {
            addCriterion("course_id not in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdBetween(Short value1, Short value2) {
            addCriterion("course_id between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotBetween(Short value1, Short value2) {
            addCriterion("course_id not between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andMkpaperTermIsNull() {
            addCriterion("mkpaper_term is null");
            return (Criteria) this;
        }

        public Criteria andMkpaperTermIsNotNull() {
            addCriterion("mkpaper_term is not null");
            return (Criteria) this;
        }

        public Criteria andMkpaperTermEqualTo(String value) {
            addCriterion("mkpaper_term =", value, "mkpaperTerm");
            return (Criteria) this;
        }

        public Criteria andMkpaperTermNotEqualTo(String value) {
            addCriterion("mkpaper_term <>", value, "mkpaperTerm");
            return (Criteria) this;
        }

        public Criteria andMkpaperTermGreaterThan(String value) {
            addCriterion("mkpaper_term >", value, "mkpaperTerm");
            return (Criteria) this;
        }

        public Criteria andMkpaperTermGreaterThanOrEqualTo(String value) {
            addCriterion("mkpaper_term >=", value, "mkpaperTerm");
            return (Criteria) this;
        }

        public Criteria andMkpaperTermLessThan(String value) {
            addCriterion("mkpaper_term <", value, "mkpaperTerm");
            return (Criteria) this;
        }

        public Criteria andMkpaperTermLessThanOrEqualTo(String value) {
            addCriterion("mkpaper_term <=", value, "mkpaperTerm");
            return (Criteria) this;
        }

        public Criteria andMkpaperTermLike(String value) {
            addCriterion("mkpaper_term like", value, "mkpaperTerm");
            return (Criteria) this;
        }

        public Criteria andMkpaperTermNotLike(String value) {
            addCriterion("mkpaper_term not like", value, "mkpaperTerm");
            return (Criteria) this;
        }

        public Criteria andMkpaperTermIn(List<String> values) {
            addCriterion("mkpaper_term in", values, "mkpaperTerm");
            return (Criteria) this;
        }

        public Criteria andMkpaperTermNotIn(List<String> values) {
            addCriterion("mkpaper_term not in", values, "mkpaperTerm");
            return (Criteria) this;
        }

        public Criteria andMkpaperTermBetween(String value1, String value2) {
            addCriterion("mkpaper_term between", value1, value2, "mkpaperTerm");
            return (Criteria) this;
        }

        public Criteria andMkpaperTermNotBetween(String value1, String value2) {
            addCriterion("mkpaper_term not between", value1, value2, "mkpaperTerm");
            return (Criteria) this;
        }

        public Criteria andMkpaperExtimeIsNull() {
            addCriterion("mkpaper_extime is null");
            return (Criteria) this;
        }

        public Criteria andMkpaperExtimeIsNotNull() {
            addCriterion("mkpaper_extime is not null");
            return (Criteria) this;
        }

        public Criteria andMkpaperExtimeEqualTo(Short value) {
            addCriterion("mkpaper_extime =", value, "mkpaperExtime");
            return (Criteria) this;
        }

        public Criteria andMkpaperExtimeNotEqualTo(Short value) {
            addCriterion("mkpaper_extime <>", value, "mkpaperExtime");
            return (Criteria) this;
        }

        public Criteria andMkpaperExtimeGreaterThan(Short value) {
            addCriterion("mkpaper_extime >", value, "mkpaperExtime");
            return (Criteria) this;
        }

        public Criteria andMkpaperExtimeGreaterThanOrEqualTo(Short value) {
            addCriterion("mkpaper_extime >=", value, "mkpaperExtime");
            return (Criteria) this;
        }

        public Criteria andMkpaperExtimeLessThan(Short value) {
            addCriterion("mkpaper_extime <", value, "mkpaperExtime");
            return (Criteria) this;
        }

        public Criteria andMkpaperExtimeLessThanOrEqualTo(Short value) {
            addCriterion("mkpaper_extime <=", value, "mkpaperExtime");
            return (Criteria) this;
        }

        public Criteria andMkpaperExtimeIn(List<Short> values) {
            addCriterion("mkpaper_extime in", values, "mkpaperExtime");
            return (Criteria) this;
        }

        public Criteria andMkpaperExtimeNotIn(List<Short> values) {
            addCriterion("mkpaper_extime not in", values, "mkpaperExtime");
            return (Criteria) this;
        }

        public Criteria andMkpaperExtimeBetween(Short value1, Short value2) {
            addCriterion("mkpaper_extime between", value1, value2, "mkpaperExtime");
            return (Criteria) this;
        }

        public Criteria andMkpaperExtimeNotBetween(Short value1, Short value2) {
            addCriterion("mkpaper_extime not between", value1, value2, "mkpaperExtime");
            return (Criteria) this;
        }

        public Criteria andMkpaperScoreIsNull() {
            addCriterion("mkpaper_score is null");
            return (Criteria) this;
        }

        public Criteria andMkpaperScoreIsNotNull() {
            addCriterion("mkpaper_score is not null");
            return (Criteria) this;
        }

        public Criteria andMkpaperScoreEqualTo(Short value) {
            addCriterion("mkpaper_score =", value, "mkpaperScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperScoreNotEqualTo(Short value) {
            addCriterion("mkpaper_score <>", value, "mkpaperScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperScoreGreaterThan(Short value) {
            addCriterion("mkpaper_score >", value, "mkpaperScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperScoreGreaterThanOrEqualTo(Short value) {
            addCriterion("mkpaper_score >=", value, "mkpaperScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperScoreLessThan(Short value) {
            addCriterion("mkpaper_score <", value, "mkpaperScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperScoreLessThanOrEqualTo(Short value) {
            addCriterion("mkpaper_score <=", value, "mkpaperScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperScoreIn(List<Short> values) {
            addCriterion("mkpaper_score in", values, "mkpaperScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperScoreNotIn(List<Short> values) {
            addCriterion("mkpaper_score not in", values, "mkpaperScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperScoreBetween(Short value1, Short value2) {
            addCriterion("mkpaper_score between", value1, value2, "mkpaperScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperScoreNotBetween(Short value1, Short value2) {
            addCriterion("mkpaper_score not between", value1, value2, "mkpaperScore");
            return (Criteria) this;
        }

        public Criteria andMkpaperTypeIsNull() {
            addCriterion("mkpaper_type is null");
            return (Criteria) this;
        }

        public Criteria andMkpaperTypeIsNotNull() {
            addCriterion("mkpaper_type is not null");
            return (Criteria) this;
        }

        public Criteria andMkpaperTypeEqualTo(Boolean value) {
            addCriterion("mkpaper_type =", value, "mkpaperType");
            return (Criteria) this;
        }

        public Criteria andMkpaperTypeNotEqualTo(Boolean value) {
            addCriterion("mkpaper_type <>", value, "mkpaperType");
            return (Criteria) this;
        }

        public Criteria andMkpaperTypeGreaterThan(Boolean value) {
            addCriterion("mkpaper_type >", value, "mkpaperType");
            return (Criteria) this;
        }

        public Criteria andMkpaperTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("mkpaper_type >=", value, "mkpaperType");
            return (Criteria) this;
        }

        public Criteria andMkpaperTypeLessThan(Boolean value) {
            addCriterion("mkpaper_type <", value, "mkpaperType");
            return (Criteria) this;
        }

        public Criteria andMkpaperTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("mkpaper_type <=", value, "mkpaperType");
            return (Criteria) this;
        }

        public Criteria andMkpaperTypeIn(List<Boolean> values) {
            addCriterion("mkpaper_type in", values, "mkpaperType");
            return (Criteria) this;
        }

        public Criteria andMkpaperTypeNotIn(List<Boolean> values) {
            addCriterion("mkpaper_type not in", values, "mkpaperType");
            return (Criteria) this;
        }

        public Criteria andMkpaperTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("mkpaper_type between", value1, value2, "mkpaperType");
            return (Criteria) this;
        }

        public Criteria andMkpaperTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("mkpaper_type not between", value1, value2, "mkpaperType");
            return (Criteria) this;
        }

        public Criteria andPpassportIdIsNull() {
            addCriterion("ppassport_id is null");
            return (Criteria) this;
        }

        public Criteria andPpassportIdIsNotNull() {
            addCriterion("ppassport_id is not null");
            return (Criteria) this;
        }

        public Criteria andPpassportIdEqualTo(Long value) {
            addCriterion("ppassport_id =", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdNotEqualTo(Long value) {
            addCriterion("ppassport_id <>", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdGreaterThan(Long value) {
            addCriterion("ppassport_id >", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ppassport_id >=", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdLessThan(Long value) {
            addCriterion("ppassport_id <", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdLessThanOrEqualTo(Long value) {
            addCriterion("ppassport_id <=", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdIn(List<Long> values) {
            addCriterion("ppassport_id in", values, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdNotIn(List<Long> values) {
            addCriterion("ppassport_id not in", values, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdBetween(Long value1, Long value2) {
            addCriterion("ppassport_id between", value1, value2, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdNotBetween(Long value1, Long value2) {
            addCriterion("ppassport_id not between", value1, value2, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeIsNull() {
            addCriterion("ppassport_time is null");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeIsNotNull() {
            addCriterion("ppassport_time is not null");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeEqualTo(Date value) {
            addCriterion("ppassport_time =", value, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeNotEqualTo(Date value) {
            addCriterion("ppassport_time <>", value, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeGreaterThan(Date value) {
            addCriterion("ppassport_time >", value, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ppassport_time >=", value, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeLessThan(Date value) {
            addCriterion("ppassport_time <", value, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeLessThanOrEqualTo(Date value) {
            addCriterion("ppassport_time <=", value, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeIn(List<Date> values) {
            addCriterion("ppassport_time in", values, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeNotIn(List<Date> values) {
            addCriterion("ppassport_time not in", values, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeBetween(Date value1, Date value2) {
            addCriterion("ppassport_time between", value1, value2, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeNotBetween(Date value1, Date value2) {
            addCriterion("ppassport_time not between", value1, value2, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPaperNameIsNull() {
            addCriterion("paper_name is null");
            return (Criteria) this;
        }

        public Criteria andPaperNameIsNotNull() {
            addCriterion("paper_name is not null");
            return (Criteria) this;
        }

        public Criteria andPaperNameEqualTo(String value) {
            addCriterion("paper_name =", value, "paperName");
            return (Criteria) this;
        }

        public Criteria andPaperNameNotEqualTo(String value) {
            addCriterion("paper_name <>", value, "paperName");
            return (Criteria) this;
        }

        public Criteria andPaperNameGreaterThan(String value) {
            addCriterion("paper_name >", value, "paperName");
            return (Criteria) this;
        }

        public Criteria andPaperNameGreaterThanOrEqualTo(String value) {
            addCriterion("paper_name >=", value, "paperName");
            return (Criteria) this;
        }

        public Criteria andPaperNameLessThan(String value) {
            addCriterion("paper_name <", value, "paperName");
            return (Criteria) this;
        }

        public Criteria andPaperNameLessThanOrEqualTo(String value) {
            addCriterion("paper_name <=", value, "paperName");
            return (Criteria) this;
        }

        public Criteria andPaperNameLike(String value) {
            addCriterion("paper_name like", value, "paperName");
            return (Criteria) this;
        }

        public Criteria andPaperNameNotLike(String value) {
            addCriterion("paper_name not like", value, "paperName");
            return (Criteria) this;
        }

        public Criteria andPaperNameIn(List<String> values) {
            addCriterion("paper_name in", values, "paperName");
            return (Criteria) this;
        }

        public Criteria andPaperNameNotIn(List<String> values) {
            addCriterion("paper_name not in", values, "paperName");
            return (Criteria) this;
        }

        public Criteria andPaperNameBetween(String value1, String value2) {
            addCriterion("paper_name between", value1, value2, "paperName");
            return (Criteria) this;
        }

        public Criteria andPaperNameNotBetween(String value1, String value2) {
            addCriterion("paper_name not between", value1, value2, "paperName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_mkpaper
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 12 20:45:29 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_mkpaper
     *
     * @mbggenerated Tue Apr 12 20:45:29 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}