package sei.tk.service.dao.model;

public class TkProgress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_progress.pro_uuid
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long proUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_progress.stu_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_progress.course_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Short courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_progress.pro_course
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Byte proCourse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_progress.pro_chapter
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private String proChapter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_progress.pro_uuid
     *
     * @return the value of tk_progress.pro_uuid
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getProUuid() {
        return proUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_progress.pro_uuid
     *
     * @param proUuid the value for tk_progress.pro_uuid
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setProUuid(Long proUuid) {
        this.proUuid = proUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_progress.stu_id
     *
     * @return the value of tk_progress.stu_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_progress.stu_id
     *
     * @param stuId the value for tk_progress.stu_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setStuId(Long stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_progress.course_id
     *
     * @return the value of tk_progress.course_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Short getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_progress.course_id
     *
     * @param courseId the value for tk_progress.course_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setCourseId(Short courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_progress.pro_course
     *
     * @return the value of tk_progress.pro_course
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Byte getProCourse() {
        return proCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_progress.pro_course
     *
     * @param proCourse the value for tk_progress.pro_course
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setProCourse(Byte proCourse) {
        this.proCourse = proCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_progress.pro_chapter
     *
     * @return the value of tk_progress.pro_chapter
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public String getProChapter() {
        return proChapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_progress.pro_chapter
     *
     * @param proChapter the value for tk_progress.pro_chapter
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setProChapter(String proChapter) {
        this.proChapter = proChapter;
    }
}