package sei.tk.service.dao.model;

public class TkQuecoll {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_quecoll.quecoll_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long quecollId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_quecoll.stu_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_quecoll.subject_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_quecoll.quecoll_answer
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private String quecollAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_quecoll.quecoll_memo
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private String quecollMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_quecoll.quecoll_id
     *
     * @return the value of tk_quecoll.quecoll_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getQuecollId() {
        return quecollId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_quecoll.quecoll_id
     *
     * @param quecollId the value for tk_quecoll.quecoll_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setQuecollId(Long quecollId) {
        this.quecollId = quecollId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_quecoll.stu_id
     *
     * @return the value of tk_quecoll.stu_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_quecoll.stu_id
     *
     * @param stuId the value for tk_quecoll.stu_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setStuId(Long stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_quecoll.subject_id
     *
     * @return the value of tk_quecoll.subject_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_quecoll.subject_id
     *
     * @param subjectId the value for tk_quecoll.subject_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_quecoll.quecoll_answer
     *
     * @return the value of tk_quecoll.quecoll_answer
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public String getQuecollAnswer() {
        return quecollAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_quecoll.quecoll_answer
     *
     * @param quecollAnswer the value for tk_quecoll.quecoll_answer
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setQuecollAnswer(String quecollAnswer) {
        this.quecollAnswer = quecollAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_quecoll.quecoll_memo
     *
     * @return the value of tk_quecoll.quecoll_memo
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public String getQuecollMemo() {
        return quecollMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_quecoll.quecoll_memo
     *
     * @param quecollMemo the value for tk_quecoll.quecoll_memo
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setQuecollMemo(String quecollMemo) {
        this.quecollMemo = quecollMemo;
    }
}