package sei.tk.service.dao.model;

import java.util.ArrayList;
import java.util.List;

public class TkQuetypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_quetype
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_quetype
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_quetype
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quetype
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public TkQuetypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quetype
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quetype
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quetype
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quetype
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quetype
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quetype
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quetype
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quetype
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quetype
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quetype
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_quetype
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuetypeIdIsNull() {
            addCriterion("quetype_id is null");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdIsNotNull() {
            addCriterion("quetype_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdEqualTo(Short value) {
            addCriterion("quetype_id =", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdNotEqualTo(Short value) {
            addCriterion("quetype_id <>", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdGreaterThan(Short value) {
            addCriterion("quetype_id >", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdGreaterThanOrEqualTo(Short value) {
            addCriterion("quetype_id >=", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdLessThan(Short value) {
            addCriterion("quetype_id <", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdLessThanOrEqualTo(Short value) {
            addCriterion("quetype_id <=", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdIn(List<Short> values) {
            addCriterion("quetype_id in", values, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdNotIn(List<Short> values) {
            addCriterion("quetype_id not in", values, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdBetween(Short value1, Short value2) {
            addCriterion("quetype_id between", value1, value2, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdNotBetween(Short value1, Short value2) {
            addCriterion("quetype_id not between", value1, value2, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeNameIsNull() {
            addCriterion("quetype_name is null");
            return (Criteria) this;
        }

        public Criteria andQuetypeNameIsNotNull() {
            addCriterion("quetype_name is not null");
            return (Criteria) this;
        }

        public Criteria andQuetypeNameEqualTo(String value) {
            addCriterion("quetype_name =", value, "quetypeName");
            return (Criteria) this;
        }

        public Criteria andQuetypeNameNotEqualTo(String value) {
            addCriterion("quetype_name <>", value, "quetypeName");
            return (Criteria) this;
        }

        public Criteria andQuetypeNameGreaterThan(String value) {
            addCriterion("quetype_name >", value, "quetypeName");
            return (Criteria) this;
        }

        public Criteria andQuetypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("quetype_name >=", value, "quetypeName");
            return (Criteria) this;
        }

        public Criteria andQuetypeNameLessThan(String value) {
            addCriterion("quetype_name <", value, "quetypeName");
            return (Criteria) this;
        }

        public Criteria andQuetypeNameLessThanOrEqualTo(String value) {
            addCriterion("quetype_name <=", value, "quetypeName");
            return (Criteria) this;
        }

        public Criteria andQuetypeNameLike(String value) {
            addCriterion("quetype_name like", value, "quetypeName");
            return (Criteria) this;
        }

        public Criteria andQuetypeNameNotLike(String value) {
            addCriterion("quetype_name not like", value, "quetypeName");
            return (Criteria) this;
        }

        public Criteria andQuetypeNameIn(List<String> values) {
            addCriterion("quetype_name in", values, "quetypeName");
            return (Criteria) this;
        }

        public Criteria andQuetypeNameNotIn(List<String> values) {
            addCriterion("quetype_name not in", values, "quetypeName");
            return (Criteria) this;
        }

        public Criteria andQuetypeNameBetween(String value1, String value2) {
            addCriterion("quetype_name between", value1, value2, "quetypeName");
            return (Criteria) this;
        }

        public Criteria andQuetypeNameNotBetween(String value1, String value2) {
            addCriterion("quetype_name not between", value1, value2, "quetypeName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_quetype
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 23 12:38:48 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_quetype
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}