package sei.tk.service.dao.model;

import java.util.ArrayList;
import java.util.List;

public class TkQuecollExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_quecoll
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_quecoll
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_quecoll
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quecoll
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public TkQuecollExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quecoll
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quecoll
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quecoll
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quecoll
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quecoll
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quecoll
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quecoll
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quecoll
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quecoll
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_quecoll
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_quecoll
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuecollIdIsNull() {
            addCriterion("quecoll_id is null");
            return (Criteria) this;
        }

        public Criteria andQuecollIdIsNotNull() {
            addCriterion("quecoll_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuecollIdEqualTo(Long value) {
            addCriterion("quecoll_id =", value, "quecollId");
            return (Criteria) this;
        }

        public Criteria andQuecollIdNotEqualTo(Long value) {
            addCriterion("quecoll_id <>", value, "quecollId");
            return (Criteria) this;
        }

        public Criteria andQuecollIdGreaterThan(Long value) {
            addCriterion("quecoll_id >", value, "quecollId");
            return (Criteria) this;
        }

        public Criteria andQuecollIdGreaterThanOrEqualTo(Long value) {
            addCriterion("quecoll_id >=", value, "quecollId");
            return (Criteria) this;
        }

        public Criteria andQuecollIdLessThan(Long value) {
            addCriterion("quecoll_id <", value, "quecollId");
            return (Criteria) this;
        }

        public Criteria andQuecollIdLessThanOrEqualTo(Long value) {
            addCriterion("quecoll_id <=", value, "quecollId");
            return (Criteria) this;
        }

        public Criteria andQuecollIdIn(List<Long> values) {
            addCriterion("quecoll_id in", values, "quecollId");
            return (Criteria) this;
        }

        public Criteria andQuecollIdNotIn(List<Long> values) {
            addCriterion("quecoll_id not in", values, "quecollId");
            return (Criteria) this;
        }

        public Criteria andQuecollIdBetween(Long value1, Long value2) {
            addCriterion("quecoll_id between", value1, value2, "quecollId");
            return (Criteria) this;
        }

        public Criteria andQuecollIdNotBetween(Long value1, Long value2) {
            addCriterion("quecoll_id not between", value1, value2, "quecollId");
            return (Criteria) this;
        }

        public Criteria andStuIdIsNull() {
            addCriterion("stu_id is null");
            return (Criteria) this;
        }

        public Criteria andStuIdIsNotNull() {
            addCriterion("stu_id is not null");
            return (Criteria) this;
        }

        public Criteria andStuIdEqualTo(Long value) {
            addCriterion("stu_id =", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotEqualTo(Long value) {
            addCriterion("stu_id <>", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdGreaterThan(Long value) {
            addCriterion("stu_id >", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("stu_id >=", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLessThan(Long value) {
            addCriterion("stu_id <", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLessThanOrEqualTo(Long value) {
            addCriterion("stu_id <=", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdIn(List<Long> values) {
            addCriterion("stu_id in", values, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotIn(List<Long> values) {
            addCriterion("stu_id not in", values, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdBetween(Long value1, Long value2) {
            addCriterion("stu_id between", value1, value2, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotBetween(Long value1, Long value2) {
            addCriterion("stu_id not between", value1, value2, "stuId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNull() {
            addCriterion("subject_id is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNotNull() {
            addCriterion("subject_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdEqualTo(Long value) {
            addCriterion("subject_id =", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotEqualTo(Long value) {
            addCriterion("subject_id <>", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThan(Long value) {
            addCriterion("subject_id >", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThanOrEqualTo(Long value) {
            addCriterion("subject_id >=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThan(Long value) {
            addCriterion("subject_id <", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThanOrEqualTo(Long value) {
            addCriterion("subject_id <=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIn(List<Long> values) {
            addCriterion("subject_id in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotIn(List<Long> values) {
            addCriterion("subject_id not in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdBetween(Long value1, Long value2) {
            addCriterion("subject_id between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotBetween(Long value1, Long value2) {
            addCriterion("subject_id not between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andQuecollAnswerIsNull() {
            addCriterion("quecoll_answer is null");
            return (Criteria) this;
        }

        public Criteria andQuecollAnswerIsNotNull() {
            addCriterion("quecoll_answer is not null");
            return (Criteria) this;
        }

        public Criteria andQuecollAnswerEqualTo(String value) {
            addCriterion("quecoll_answer =", value, "quecollAnswer");
            return (Criteria) this;
        }

        public Criteria andQuecollAnswerNotEqualTo(String value) {
            addCriterion("quecoll_answer <>", value, "quecollAnswer");
            return (Criteria) this;
        }

        public Criteria andQuecollAnswerGreaterThan(String value) {
            addCriterion("quecoll_answer >", value, "quecollAnswer");
            return (Criteria) this;
        }

        public Criteria andQuecollAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("quecoll_answer >=", value, "quecollAnswer");
            return (Criteria) this;
        }

        public Criteria andQuecollAnswerLessThan(String value) {
            addCriterion("quecoll_answer <", value, "quecollAnswer");
            return (Criteria) this;
        }

        public Criteria andQuecollAnswerLessThanOrEqualTo(String value) {
            addCriterion("quecoll_answer <=", value, "quecollAnswer");
            return (Criteria) this;
        }

        public Criteria andQuecollAnswerLike(String value) {
            addCriterion("quecoll_answer like", value, "quecollAnswer");
            return (Criteria) this;
        }

        public Criteria andQuecollAnswerNotLike(String value) {
            addCriterion("quecoll_answer not like", value, "quecollAnswer");
            return (Criteria) this;
        }

        public Criteria andQuecollAnswerIn(List<String> values) {
            addCriterion("quecoll_answer in", values, "quecollAnswer");
            return (Criteria) this;
        }

        public Criteria andQuecollAnswerNotIn(List<String> values) {
            addCriterion("quecoll_answer not in", values, "quecollAnswer");
            return (Criteria) this;
        }

        public Criteria andQuecollAnswerBetween(String value1, String value2) {
            addCriterion("quecoll_answer between", value1, value2, "quecollAnswer");
            return (Criteria) this;
        }

        public Criteria andQuecollAnswerNotBetween(String value1, String value2) {
            addCriterion("quecoll_answer not between", value1, value2, "quecollAnswer");
            return (Criteria) this;
        }

        public Criteria andQuecollMemoIsNull() {
            addCriterion("quecoll_memo is null");
            return (Criteria) this;
        }

        public Criteria andQuecollMemoIsNotNull() {
            addCriterion("quecoll_memo is not null");
            return (Criteria) this;
        }

        public Criteria andQuecollMemoEqualTo(String value) {
            addCriterion("quecoll_memo =", value, "quecollMemo");
            return (Criteria) this;
        }

        public Criteria andQuecollMemoNotEqualTo(String value) {
            addCriterion("quecoll_memo <>", value, "quecollMemo");
            return (Criteria) this;
        }

        public Criteria andQuecollMemoGreaterThan(String value) {
            addCriterion("quecoll_memo >", value, "quecollMemo");
            return (Criteria) this;
        }

        public Criteria andQuecollMemoGreaterThanOrEqualTo(String value) {
            addCriterion("quecoll_memo >=", value, "quecollMemo");
            return (Criteria) this;
        }

        public Criteria andQuecollMemoLessThan(String value) {
            addCriterion("quecoll_memo <", value, "quecollMemo");
            return (Criteria) this;
        }

        public Criteria andQuecollMemoLessThanOrEqualTo(String value) {
            addCriterion("quecoll_memo <=", value, "quecollMemo");
            return (Criteria) this;
        }

        public Criteria andQuecollMemoLike(String value) {
            addCriterion("quecoll_memo like", value, "quecollMemo");
            return (Criteria) this;
        }

        public Criteria andQuecollMemoNotLike(String value) {
            addCriterion("quecoll_memo not like", value, "quecollMemo");
            return (Criteria) this;
        }

        public Criteria andQuecollMemoIn(List<String> values) {
            addCriterion("quecoll_memo in", values, "quecollMemo");
            return (Criteria) this;
        }

        public Criteria andQuecollMemoNotIn(List<String> values) {
            addCriterion("quecoll_memo not in", values, "quecollMemo");
            return (Criteria) this;
        }

        public Criteria andQuecollMemoBetween(String value1, String value2) {
            addCriterion("quecoll_memo between", value1, value2, "quecollMemo");
            return (Criteria) this;
        }

        public Criteria andQuecollMemoNotBetween(String value1, String value2) {
            addCriterion("quecoll_memo not between", value1, value2, "quecollMemo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_quecoll
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 23 12:38:48 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_quecoll
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}