package sei.tk.service.dao.model;

import java.util.ArrayList;
import java.util.List;

public class TkSelectcourseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_selectcourse
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_selectcourse
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_selectcourse
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_selectcourse
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public TkSelectcourseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_selectcourse
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_selectcourse
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_selectcourse
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_selectcourse
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_selectcourse
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_selectcourse
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_selectcourse
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_selectcourse
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_selectcourse
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_selectcourse
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_selectcourse
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSelIdIsNull() {
            addCriterion("sel_Id is null");
            return (Criteria) this;
        }

        public Criteria andSelIdIsNotNull() {
            addCriterion("sel_Id is not null");
            return (Criteria) this;
        }

        public Criteria andSelIdEqualTo(Long value) {
            addCriterion("sel_Id =", value, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdNotEqualTo(Long value) {
            addCriterion("sel_Id <>", value, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdGreaterThan(Long value) {
            addCriterion("sel_Id >", value, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sel_Id >=", value, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdLessThan(Long value) {
            addCriterion("sel_Id <", value, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdLessThanOrEqualTo(Long value) {
            addCriterion("sel_Id <=", value, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdIn(List<Long> values) {
            addCriterion("sel_Id in", values, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdNotIn(List<Long> values) {
            addCriterion("sel_Id not in", values, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdBetween(Long value1, Long value2) {
            addCriterion("sel_Id between", value1, value2, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdNotBetween(Long value1, Long value2) {
            addCriterion("sel_Id not between", value1, value2, "selId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdIsNull() {
            addCriterion("ppassport_id is null");
            return (Criteria) this;
        }

        public Criteria andPpassportIdIsNotNull() {
            addCriterion("ppassport_id is not null");
            return (Criteria) this;
        }

        public Criteria andPpassportIdEqualTo(Long value) {
            addCriterion("ppassport_id =", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdNotEqualTo(Long value) {
            addCriterion("ppassport_id <>", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdGreaterThan(Long value) {
            addCriterion("ppassport_id >", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ppassport_id >=", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdLessThan(Long value) {
            addCriterion("ppassport_id <", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdLessThanOrEqualTo(Long value) {
            addCriterion("ppassport_id <=", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdIn(List<Long> values) {
            addCriterion("ppassport_id in", values, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdNotIn(List<Long> values) {
            addCriterion("ppassport_id not in", values, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdBetween(Long value1, Long value2) {
            addCriterion("ppassport_id between", value1, value2, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdNotBetween(Long value1, Long value2) {
            addCriterion("ppassport_id not between", value1, value2, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNull() {
            addCriterion("course_id is null");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNotNull() {
            addCriterion("course_id is not null");
            return (Criteria) this;
        }

        public Criteria andCourseIdEqualTo(Short value) {
            addCriterion("course_id =", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotEqualTo(Short value) {
            addCriterion("course_id <>", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThan(Short value) {
            addCriterion("course_id >", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThanOrEqualTo(Short value) {
            addCriterion("course_id >=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThan(Short value) {
            addCriterion("course_id <", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThanOrEqualTo(Short value) {
            addCriterion("course_id <=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdIn(List<Short> values) {
            addCriterion("course_id in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotIn(List<Short> values) {
            addCriterion("course_id not in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdBetween(Short value1, Short value2) {
            addCriterion("course_id between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotBetween(Short value1, Short value2) {
            addCriterion("course_id not between", value1, value2, "courseId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_selectcourse
     *
     * @mbggenerated do_not_delete_during_merge Sat Mar 26 15:38:24 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_selectcourse
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}