package sei.tk.service.dao.model;

public class TkSelectcourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_selectcourse.sel_Id
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    private Long selId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_selectcourse.ppassport_id
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    private Long ppassportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_selectcourse.course_id
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    private Short courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_selectcourse.sel_Id
     *
     * @return the value of tk_selectcourse.sel_Id
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public Long getSelId() {
        return selId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_selectcourse.sel_Id
     *
     * @param selId the value for tk_selectcourse.sel_Id
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public void setSelId(Long selId) {
        this.selId = selId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_selectcourse.ppassport_id
     *
     * @return the value of tk_selectcourse.ppassport_id
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public Long getPpassportId() {
        return ppassportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_selectcourse.ppassport_id
     *
     * @param ppassportId the value for tk_selectcourse.ppassport_id
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public void setPpassportId(Long ppassportId) {
        this.ppassportId = ppassportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_selectcourse.course_id
     *
     * @return the value of tk_selectcourse.course_id
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public Short getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_selectcourse.course_id
     *
     * @param courseId the value for tk_selectcourse.course_id
     *
     * @mbggenerated Sat Mar 26 15:38:24 CST 2016
     */
    public void setCourseId(Short courseId) {
        this.courseId = courseId;
    }
}