package sei.tk.service.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TkStudentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public TkStudentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPpassportIdIsNull() {
            addCriterion("ppassport_id is null");
            return (Criteria) this;
        }

        public Criteria andPpassportIdIsNotNull() {
            addCriterion("ppassport_id is not null");
            return (Criteria) this;
        }

        public Criteria andPpassportIdEqualTo(Long value) {
            addCriterion("ppassport_id =", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdNotEqualTo(Long value) {
            addCriterion("ppassport_id <>", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdGreaterThan(Long value) {
            addCriterion("ppassport_id >", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ppassport_id >=", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdLessThan(Long value) {
            addCriterion("ppassport_id <", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdLessThanOrEqualTo(Long value) {
            addCriterion("ppassport_id <=", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdIn(List<Long> values) {
            addCriterion("ppassport_id in", values, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdNotIn(List<Long> values) {
            addCriterion("ppassport_id not in", values, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdBetween(Long value1, Long value2) {
            addCriterion("ppassport_id between", value1, value2, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdNotBetween(Long value1, Long value2) {
            addCriterion("ppassport_id not between", value1, value2, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andStuCodeIsNull() {
            addCriterion("stu_code is null");
            return (Criteria) this;
        }

        public Criteria andStuCodeIsNotNull() {
            addCriterion("stu_code is not null");
            return (Criteria) this;
        }

        public Criteria andStuCodeEqualTo(String value) {
            addCriterion("stu_code =", value, "stuCode");
            return (Criteria) this;
        }

        public Criteria andStuCodeNotEqualTo(String value) {
            addCriterion("stu_code <>", value, "stuCode");
            return (Criteria) this;
        }

        public Criteria andStuCodeGreaterThan(String value) {
            addCriterion("stu_code >", value, "stuCode");
            return (Criteria) this;
        }

        public Criteria andStuCodeGreaterThanOrEqualTo(String value) {
            addCriterion("stu_code >=", value, "stuCode");
            return (Criteria) this;
        }

        public Criteria andStuCodeLessThan(String value) {
            addCriterion("stu_code <", value, "stuCode");
            return (Criteria) this;
        }

        public Criteria andStuCodeLessThanOrEqualTo(String value) {
            addCriterion("stu_code <=", value, "stuCode");
            return (Criteria) this;
        }

        public Criteria andStuCodeLike(String value) {
            addCriterion("stu_code like", value, "stuCode");
            return (Criteria) this;
        }

        public Criteria andStuCodeNotLike(String value) {
            addCriterion("stu_code not like", value, "stuCode");
            return (Criteria) this;
        }

        public Criteria andStuCodeIn(List<String> values) {
            addCriterion("stu_code in", values, "stuCode");
            return (Criteria) this;
        }

        public Criteria andStuCodeNotIn(List<String> values) {
            addCriterion("stu_code not in", values, "stuCode");
            return (Criteria) this;
        }

        public Criteria andStuCodeBetween(String value1, String value2) {
            addCriterion("stu_code between", value1, value2, "stuCode");
            return (Criteria) this;
        }

        public Criteria andStuCodeNotBetween(String value1, String value2) {
            addCriterion("stu_code not between", value1, value2, "stuCode");
            return (Criteria) this;
        }

        public Criteria andStuNameIsNull() {
            addCriterion("stu_name is null");
            return (Criteria) this;
        }

        public Criteria andStuNameIsNotNull() {
            addCriterion("stu_name is not null");
            return (Criteria) this;
        }

        public Criteria andStuNameEqualTo(String value) {
            addCriterion("stu_name =", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotEqualTo(String value) {
            addCriterion("stu_name <>", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameGreaterThan(String value) {
            addCriterion("stu_name >", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameGreaterThanOrEqualTo(String value) {
            addCriterion("stu_name >=", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameLessThan(String value) {
            addCriterion("stu_name <", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameLessThanOrEqualTo(String value) {
            addCriterion("stu_name <=", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameLike(String value) {
            addCriterion("stu_name like", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotLike(String value) {
            addCriterion("stu_name not like", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameIn(List<String> values) {
            addCriterion("stu_name in", values, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotIn(List<String> values) {
            addCriterion("stu_name not in", values, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameBetween(String value1, String value2) {
            addCriterion("stu_name between", value1, value2, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotBetween(String value1, String value2) {
            addCriterion("stu_name not between", value1, value2, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuGenderIsNull() {
            addCriterion("stu_gender is null");
            return (Criteria) this;
        }

        public Criteria andStuGenderIsNotNull() {
            addCriterion("stu_gender is not null");
            return (Criteria) this;
        }

        public Criteria andStuGenderEqualTo(String value) {
            addCriterion("stu_gender =", value, "stuGender");
            return (Criteria) this;
        }

        public Criteria andStuGenderNotEqualTo(String value) {
            addCriterion("stu_gender <>", value, "stuGender");
            return (Criteria) this;
        }

        public Criteria andStuGenderGreaterThan(String value) {
            addCriterion("stu_gender >", value, "stuGender");
            return (Criteria) this;
        }

        public Criteria andStuGenderGreaterThanOrEqualTo(String value) {
            addCriterion("stu_gender >=", value, "stuGender");
            return (Criteria) this;
        }

        public Criteria andStuGenderLessThan(String value) {
            addCriterion("stu_gender <", value, "stuGender");
            return (Criteria) this;
        }

        public Criteria andStuGenderLessThanOrEqualTo(String value) {
            addCriterion("stu_gender <=", value, "stuGender");
            return (Criteria) this;
        }

        public Criteria andStuGenderLike(String value) {
            addCriterion("stu_gender like", value, "stuGender");
            return (Criteria) this;
        }

        public Criteria andStuGenderNotLike(String value) {
            addCriterion("stu_gender not like", value, "stuGender");
            return (Criteria) this;
        }

        public Criteria andStuGenderIn(List<String> values) {
            addCriterion("stu_gender in", values, "stuGender");
            return (Criteria) this;
        }

        public Criteria andStuGenderNotIn(List<String> values) {
            addCriterion("stu_gender not in", values, "stuGender");
            return (Criteria) this;
        }

        public Criteria andStuGenderBetween(String value1, String value2) {
            addCriterion("stu_gender between", value1, value2, "stuGender");
            return (Criteria) this;
        }

        public Criteria andStuGenderNotBetween(String value1, String value2) {
            addCriterion("stu_gender not between", value1, value2, "stuGender");
            return (Criteria) this;
        }

        public Criteria andStuInstituteIsNull() {
            addCriterion("stu_institute is null");
            return (Criteria) this;
        }

        public Criteria andStuInstituteIsNotNull() {
            addCriterion("stu_institute is not null");
            return (Criteria) this;
        }

        public Criteria andStuInstituteEqualTo(String value) {
            addCriterion("stu_institute =", value, "stuInstitute");
            return (Criteria) this;
        }

        public Criteria andStuInstituteNotEqualTo(String value) {
            addCriterion("stu_institute <>", value, "stuInstitute");
            return (Criteria) this;
        }

        public Criteria andStuInstituteGreaterThan(String value) {
            addCriterion("stu_institute >", value, "stuInstitute");
            return (Criteria) this;
        }

        public Criteria andStuInstituteGreaterThanOrEqualTo(String value) {
            addCriterion("stu_institute >=", value, "stuInstitute");
            return (Criteria) this;
        }

        public Criteria andStuInstituteLessThan(String value) {
            addCriterion("stu_institute <", value, "stuInstitute");
            return (Criteria) this;
        }

        public Criteria andStuInstituteLessThanOrEqualTo(String value) {
            addCriterion("stu_institute <=", value, "stuInstitute");
            return (Criteria) this;
        }

        public Criteria andStuInstituteLike(String value) {
            addCriterion("stu_institute like", value, "stuInstitute");
            return (Criteria) this;
        }

        public Criteria andStuInstituteNotLike(String value) {
            addCriterion("stu_institute not like", value, "stuInstitute");
            return (Criteria) this;
        }

        public Criteria andStuInstituteIn(List<String> values) {
            addCriterion("stu_institute in", values, "stuInstitute");
            return (Criteria) this;
        }

        public Criteria andStuInstituteNotIn(List<String> values) {
            addCriterion("stu_institute not in", values, "stuInstitute");
            return (Criteria) this;
        }

        public Criteria andStuInstituteBetween(String value1, String value2) {
            addCriterion("stu_institute between", value1, value2, "stuInstitute");
            return (Criteria) this;
        }

        public Criteria andStuInstituteNotBetween(String value1, String value2) {
            addCriterion("stu_institute not between", value1, value2, "stuInstitute");
            return (Criteria) this;
        }

        public Criteria andStuMajorIsNull() {
            addCriterion("stu_major is null");
            return (Criteria) this;
        }

        public Criteria andStuMajorIsNotNull() {
            addCriterion("stu_major is not null");
            return (Criteria) this;
        }

        public Criteria andStuMajorEqualTo(String value) {
            addCriterion("stu_major =", value, "stuMajor");
            return (Criteria) this;
        }

        public Criteria andStuMajorNotEqualTo(String value) {
            addCriterion("stu_major <>", value, "stuMajor");
            return (Criteria) this;
        }

        public Criteria andStuMajorGreaterThan(String value) {
            addCriterion("stu_major >", value, "stuMajor");
            return (Criteria) this;
        }

        public Criteria andStuMajorGreaterThanOrEqualTo(String value) {
            addCriterion("stu_major >=", value, "stuMajor");
            return (Criteria) this;
        }

        public Criteria andStuMajorLessThan(String value) {
            addCriterion("stu_major <", value, "stuMajor");
            return (Criteria) this;
        }

        public Criteria andStuMajorLessThanOrEqualTo(String value) {
            addCriterion("stu_major <=", value, "stuMajor");
            return (Criteria) this;
        }

        public Criteria andStuMajorLike(String value) {
            addCriterion("stu_major like", value, "stuMajor");
            return (Criteria) this;
        }

        public Criteria andStuMajorNotLike(String value) {
            addCriterion("stu_major not like", value, "stuMajor");
            return (Criteria) this;
        }

        public Criteria andStuMajorIn(List<String> values) {
            addCriterion("stu_major in", values, "stuMajor");
            return (Criteria) this;
        }

        public Criteria andStuMajorNotIn(List<String> values) {
            addCriterion("stu_major not in", values, "stuMajor");
            return (Criteria) this;
        }

        public Criteria andStuMajorBetween(String value1, String value2) {
            addCriterion("stu_major between", value1, value2, "stuMajor");
            return (Criteria) this;
        }

        public Criteria andStuMajorNotBetween(String value1, String value2) {
            addCriterion("stu_major not between", value1, value2, "stuMajor");
            return (Criteria) this;
        }

        public Criteria andStuClassIdIsNull() {
            addCriterion("stu_class_id is null");
            return (Criteria) this;
        }

        public Criteria andStuClassIdIsNotNull() {
            addCriterion("stu_class_id is not null");
            return (Criteria) this;
        }

        public Criteria andStuClassIdEqualTo(Long value) {
            addCriterion("stu_class_id =", value, "stuClassId");
            return (Criteria) this;
        }

        public Criteria andStuClassIdNotEqualTo(Long value) {
            addCriterion("stu_class_id <>", value, "stuClassId");
            return (Criteria) this;
        }

        public Criteria andStuClassIdGreaterThan(Long value) {
            addCriterion("stu_class_id >", value, "stuClassId");
            return (Criteria) this;
        }

        public Criteria andStuClassIdGreaterThanOrEqualTo(Long value) {
            addCriterion("stu_class_id >=", value, "stuClassId");
            return (Criteria) this;
        }

        public Criteria andStuClassIdLessThan(Long value) {
            addCriterion("stu_class_id <", value, "stuClassId");
            return (Criteria) this;
        }

        public Criteria andStuClassIdLessThanOrEqualTo(Long value) {
            addCriterion("stu_class_id <=", value, "stuClassId");
            return (Criteria) this;
        }

        public Criteria andStuClassIdIn(List<Long> values) {
            addCriterion("stu_class_id in", values, "stuClassId");
            return (Criteria) this;
        }

        public Criteria andStuClassIdNotIn(List<Long> values) {
            addCriterion("stu_class_id not in", values, "stuClassId");
            return (Criteria) this;
        }

        public Criteria andStuClassIdBetween(Long value1, Long value2) {
            addCriterion("stu_class_id between", value1, value2, "stuClassId");
            return (Criteria) this;
        }

        public Criteria andStuClassIdNotBetween(Long value1, Long value2) {
            addCriterion("stu_class_id not between", value1, value2, "stuClassId");
            return (Criteria) this;
        }

        public Criteria andStuEmailIsNull() {
            addCriterion("stu_email is null");
            return (Criteria) this;
        }

        public Criteria andStuEmailIsNotNull() {
            addCriterion("stu_email is not null");
            return (Criteria) this;
        }

        public Criteria andStuEmailEqualTo(String value) {
            addCriterion("stu_email =", value, "stuEmail");
            return (Criteria) this;
        }

        public Criteria andStuEmailNotEqualTo(String value) {
            addCriterion("stu_email <>", value, "stuEmail");
            return (Criteria) this;
        }

        public Criteria andStuEmailGreaterThan(String value) {
            addCriterion("stu_email >", value, "stuEmail");
            return (Criteria) this;
        }

        public Criteria andStuEmailGreaterThanOrEqualTo(String value) {
            addCriterion("stu_email >=", value, "stuEmail");
            return (Criteria) this;
        }

        public Criteria andStuEmailLessThan(String value) {
            addCriterion("stu_email <", value, "stuEmail");
            return (Criteria) this;
        }

        public Criteria andStuEmailLessThanOrEqualTo(String value) {
            addCriterion("stu_email <=", value, "stuEmail");
            return (Criteria) this;
        }

        public Criteria andStuEmailLike(String value) {
            addCriterion("stu_email like", value, "stuEmail");
            return (Criteria) this;
        }

        public Criteria andStuEmailNotLike(String value) {
            addCriterion("stu_email not like", value, "stuEmail");
            return (Criteria) this;
        }

        public Criteria andStuEmailIn(List<String> values) {
            addCriterion("stu_email in", values, "stuEmail");
            return (Criteria) this;
        }

        public Criteria andStuEmailNotIn(List<String> values) {
            addCriterion("stu_email not in", values, "stuEmail");
            return (Criteria) this;
        }

        public Criteria andStuEmailBetween(String value1, String value2) {
            addCriterion("stu_email between", value1, value2, "stuEmail");
            return (Criteria) this;
        }

        public Criteria andStuEmailNotBetween(String value1, String value2) {
            addCriterion("stu_email not between", value1, value2, "stuEmail");
            return (Criteria) this;
        }

        public Criteria andStuTelIsNull() {
            addCriterion("stu_tel is null");
            return (Criteria) this;
        }

        public Criteria andStuTelIsNotNull() {
            addCriterion("stu_tel is not null");
            return (Criteria) this;
        }

        public Criteria andStuTelEqualTo(String value) {
            addCriterion("stu_tel =", value, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelNotEqualTo(String value) {
            addCriterion("stu_tel <>", value, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelGreaterThan(String value) {
            addCriterion("stu_tel >", value, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelGreaterThanOrEqualTo(String value) {
            addCriterion("stu_tel >=", value, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelLessThan(String value) {
            addCriterion("stu_tel <", value, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelLessThanOrEqualTo(String value) {
            addCriterion("stu_tel <=", value, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelLike(String value) {
            addCriterion("stu_tel like", value, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelNotLike(String value) {
            addCriterion("stu_tel not like", value, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelIn(List<String> values) {
            addCriterion("stu_tel in", values, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelNotIn(List<String> values) {
            addCriterion("stu_tel not in", values, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelBetween(String value1, String value2) {
            addCriterion("stu_tel between", value1, value2, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuTelNotBetween(String value1, String value2) {
            addCriterion("stu_tel not between", value1, value2, "stuTel");
            return (Criteria) this;
        }

        public Criteria andStuPasswordIsNull() {
            addCriterion("stu_password is null");
            return (Criteria) this;
        }

        public Criteria andStuPasswordIsNotNull() {
            addCriterion("stu_password is not null");
            return (Criteria) this;
        }

        public Criteria andStuPasswordEqualTo(String value) {
            addCriterion("stu_password =", value, "stuPassword");
            return (Criteria) this;
        }

        public Criteria andStuPasswordNotEqualTo(String value) {
            addCriterion("stu_password <>", value, "stuPassword");
            return (Criteria) this;
        }

        public Criteria andStuPasswordGreaterThan(String value) {
            addCriterion("stu_password >", value, "stuPassword");
            return (Criteria) this;
        }

        public Criteria andStuPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("stu_password >=", value, "stuPassword");
            return (Criteria) this;
        }

        public Criteria andStuPasswordLessThan(String value) {
            addCriterion("stu_password <", value, "stuPassword");
            return (Criteria) this;
        }

        public Criteria andStuPasswordLessThanOrEqualTo(String value) {
            addCriterion("stu_password <=", value, "stuPassword");
            return (Criteria) this;
        }

        public Criteria andStuPasswordLike(String value) {
            addCriterion("stu_password like", value, "stuPassword");
            return (Criteria) this;
        }

        public Criteria andStuPasswordNotLike(String value) {
            addCriterion("stu_password not like", value, "stuPassword");
            return (Criteria) this;
        }

        public Criteria andStuPasswordIn(List<String> values) {
            addCriterion("stu_password in", values, "stuPassword");
            return (Criteria) this;
        }

        public Criteria andStuPasswordNotIn(List<String> values) {
            addCriterion("stu_password not in", values, "stuPassword");
            return (Criteria) this;
        }

        public Criteria andStuPasswordBetween(String value1, String value2) {
            addCriterion("stu_password between", value1, value2, "stuPassword");
            return (Criteria) this;
        }

        public Criteria andStuPasswordNotBetween(String value1, String value2) {
            addCriterion("stu_password not between", value1, value2, "stuPassword");
            return (Criteria) this;
        }

        public Criteria andStuCreatetimeIsNull() {
            addCriterion("stu_createtime is null");
            return (Criteria) this;
        }

        public Criteria andStuCreatetimeIsNotNull() {
            addCriterion("stu_createtime is not null");
            return (Criteria) this;
        }

        public Criteria andStuCreatetimeEqualTo(Date value) {
            addCriterion("stu_createtime =", value, "stuCreatetime");
            return (Criteria) this;
        }

        public Criteria andStuCreatetimeNotEqualTo(Date value) {
            addCriterion("stu_createtime <>", value, "stuCreatetime");
            return (Criteria) this;
        }

        public Criteria andStuCreatetimeGreaterThan(Date value) {
            addCriterion("stu_createtime >", value, "stuCreatetime");
            return (Criteria) this;
        }

        public Criteria andStuCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("stu_createtime >=", value, "stuCreatetime");
            return (Criteria) this;
        }

        public Criteria andStuCreatetimeLessThan(Date value) {
            addCriterion("stu_createtime <", value, "stuCreatetime");
            return (Criteria) this;
        }

        public Criteria andStuCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("stu_createtime <=", value, "stuCreatetime");
            return (Criteria) this;
        }

        public Criteria andStuCreatetimeIn(List<Date> values) {
            addCriterion("stu_createtime in", values, "stuCreatetime");
            return (Criteria) this;
        }

        public Criteria andStuCreatetimeNotIn(List<Date> values) {
            addCriterion("stu_createtime not in", values, "stuCreatetime");
            return (Criteria) this;
        }

        public Criteria andStuCreatetimeBetween(Date value1, Date value2) {
            addCriterion("stu_createtime between", value1, value2, "stuCreatetime");
            return (Criteria) this;
        }

        public Criteria andStuCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("stu_createtime not between", value1, value2, "stuCreatetime");
            return (Criteria) this;
        }

        public Criteria andStuIsonlineIsNull() {
            addCriterion("stu_isonline is null");
            return (Criteria) this;
        }

        public Criteria andStuIsonlineIsNotNull() {
            addCriterion("stu_isonline is not null");
            return (Criteria) this;
        }

        public Criteria andStuIsonlineEqualTo(Boolean value) {
            addCriterion("stu_isonline =", value, "stuIsonline");
            return (Criteria) this;
        }

        public Criteria andStuIsonlineNotEqualTo(Boolean value) {
            addCriterion("stu_isonline <>", value, "stuIsonline");
            return (Criteria) this;
        }

        public Criteria andStuIsonlineGreaterThan(Boolean value) {
            addCriterion("stu_isonline >", value, "stuIsonline");
            return (Criteria) this;
        }

        public Criteria andStuIsonlineGreaterThanOrEqualTo(Boolean value) {
            addCriterion("stu_isonline >=", value, "stuIsonline");
            return (Criteria) this;
        }

        public Criteria andStuIsonlineLessThan(Boolean value) {
            addCriterion("stu_isonline <", value, "stuIsonline");
            return (Criteria) this;
        }

        public Criteria andStuIsonlineLessThanOrEqualTo(Boolean value) {
            addCriterion("stu_isonline <=", value, "stuIsonline");
            return (Criteria) this;
        }

        public Criteria andStuIsonlineIn(List<Boolean> values) {
            addCriterion("stu_isonline in", values, "stuIsonline");
            return (Criteria) this;
        }

        public Criteria andStuIsonlineNotIn(List<Boolean> values) {
            addCriterion("stu_isonline not in", values, "stuIsonline");
            return (Criteria) this;
        }

        public Criteria andStuIsonlineBetween(Boolean value1, Boolean value2) {
            addCriterion("stu_isonline between", value1, value2, "stuIsonline");
            return (Criteria) this;
        }

        public Criteria andStuIsonlineNotBetween(Boolean value1, Boolean value2) {
            addCriterion("stu_isonline not between", value1, value2, "stuIsonline");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_student
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 25 17:28:35 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_student
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}