package sei.tk.service.dao.model;

public class TkStudent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_student.student_id
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_student.passport_id
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    private Long passportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_student.stu_name
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_student.stu_gender
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    private String stuGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_student.stu_institute
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    private String stuInstitute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_student.stu_major
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    private String stuMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_student.stu_class_id
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    private Long stuClassId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_student.stu_email
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    private String stuEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_student.student_id
     *
     * @return the value of tk_student.student_id
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_student.student_id
     *
     * @param studentId the value for tk_student.student_id
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_student.passport_id
     *
     * @return the value of tk_student.passport_id
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public Long getPassportId() {
        return passportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_student.passport_id
     *
     * @param passportId the value for tk_student.passport_id
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setPassportId(Long passportId) {
        this.passportId = passportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_student.stu_name
     *
     * @return the value of tk_student.stu_name
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_student.stu_name
     *
     * @param stuName the value for tk_student.stu_name
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_student.stu_gender
     *
     * @return the value of tk_student.stu_gender
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public String getStuGender() {
        return stuGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_student.stu_gender
     *
     * @param stuGender the value for tk_student.stu_gender
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setStuGender(String stuGender) {
        this.stuGender = stuGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_student.stu_institute
     *
     * @return the value of tk_student.stu_institute
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public String getStuInstitute() {
        return stuInstitute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_student.stu_institute
     *
     * @param stuInstitute the value for tk_student.stu_institute
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setStuInstitute(String stuInstitute) {
        this.stuInstitute = stuInstitute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_student.stu_major
     *
     * @return the value of tk_student.stu_major
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public String getStuMajor() {
        return stuMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_student.stu_major
     *
     * @param stuMajor the value for tk_student.stu_major
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setStuMajor(String stuMajor) {
        this.stuMajor = stuMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_student.stu_class_id
     *
     * @return the value of tk_student.stu_class_id
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public Long getStuClassId() {
        return stuClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_student.stu_class_id
     *
     * @param stuClassId the value for tk_student.stu_class_id
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setStuClassId(Long stuClassId) {
        this.stuClassId = stuClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_student.stu_email
     *
     * @return the value of tk_student.stu_email
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public String getStuEmail() {
        return stuEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_student.stu_email
     *
     * @param stuEmail the value for tk_student.stu_email
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setStuEmail(String stuEmail) {
        this.stuEmail = stuEmail;
    }
}