package sei.tk.service.dao.model;

public class TkSubjectWithBLOBs extends TkSubject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_subject.subject_name
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private String subjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_subject.subject_option
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private String subjectOption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_subject.subject_solution
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private String subjectSolution;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_subject.subject_name
     *
     * @return the value of tk_subject.subject_name
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_subject.subject_name
     *
     * @param subjectName the value for tk_subject.subject_name
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_subject.subject_option
     *
     * @return the value of tk_subject.subject_option
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public String getSubjectOption() {
        return subjectOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_subject.subject_option
     *
     * @param subjectOption the value for tk_subject.subject_option
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setSubjectOption(String subjectOption) {
        this.subjectOption = subjectOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_subject.subject_solution
     *
     * @return the value of tk_subject.subject_solution
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public String getSubjectSolution() {
        return subjectSolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_subject.subject_solution
     *
     * @param subjectSolution the value for tk_subject.subject_solution
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setSubjectSolution(String subjectSolution) {
        this.subjectSolution = subjectSolution;
    }
}