package sei.tk.service.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TkSubjectExample {
    //分页相关
    private Integer start;
    private Integer row;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_subject
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_subject
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_subject
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public TkSubjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_subject
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public Integer getStart() {
        return start;
    }

    public void setStart(Integer start) {
        this.start = start;
    }

    public Integer getRow() {
        return row;
    }

    public void setRow(Integer row) {
        this.row = row;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_subject
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSubjectIdIsNull() {
            addCriterion("subject_id is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNotNull() {
            addCriterion("subject_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdEqualTo(Long value) {
            addCriterion("subject_id =", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotEqualTo(Long value) {
            addCriterion("subject_id <>", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThan(Long value) {
            addCriterion("subject_id >", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThanOrEqualTo(Long value) {
            addCriterion("subject_id >=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThan(Long value) {
            addCriterion("subject_id <", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThanOrEqualTo(Long value) {
            addCriterion("subject_id <=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIn(List<Long> values) {
            addCriterion("subject_id in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotIn(List<Long> values) {
            addCriterion("subject_id not in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdBetween(Long value1, Long value2) {
            addCriterion("subject_id between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotBetween(Long value1, Long value2) {
            addCriterion("subject_id not between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNull() {
            addCriterion("course_id is null");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNotNull() {
            addCriterion("course_id is not null");
            return (Criteria) this;
        }

        public Criteria andCourseIdEqualTo(Short value) {
            addCriterion("course_id =", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotEqualTo(Short value) {
            addCriterion("course_id <>", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThan(Short value) {
            addCriterion("course_id >", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThanOrEqualTo(Short value) {
            addCriterion("course_id >=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThan(Short value) {
            addCriterion("course_id <", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThanOrEqualTo(Short value) {
            addCriterion("course_id <=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdIn(List<Short> values) {
            addCriterion("course_id in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotIn(List<Short> values) {
            addCriterion("course_id not in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdBetween(Short value1, Short value2) {
            addCriterion("course_id between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotBetween(Short value1, Short value2) {
            addCriterion("course_id not between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdIsNull() {
            addCriterion("knopoint_id is null");
            return (Criteria) this;
        }

        public Criteria andKnopointIdIsNotNull() {
            addCriterion("knopoint_id is not null");
            return (Criteria) this;
        }

        public Criteria andKnopointIdEqualTo(Long value) {
            addCriterion("knopoint_id =", value, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdNotEqualTo(Long value) {
            addCriterion("knopoint_id <>", value, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdGreaterThan(Long value) {
            addCriterion("knopoint_id >", value, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdGreaterThanOrEqualTo(Long value) {
            addCriterion("knopoint_id >=", value, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdLessThan(Long value) {
            addCriterion("knopoint_id <", value, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdLessThanOrEqualTo(Long value) {
            addCriterion("knopoint_id <=", value, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdIn(List<Long> values) {
            addCriterion("knopoint_id in", values, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdNotIn(List<Long> values) {
            addCriterion("knopoint_id not in", values, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdBetween(Long value1, Long value2) {
            addCriterion("knopoint_id between", value1, value2, "knopointId");
            return (Criteria) this;
        }

        public Criteria andKnopointIdNotBetween(Long value1, Long value2) {
            addCriterion("knopoint_id not between", value1, value2, "knopointId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdIsNull() {
            addCriterion("quetype_id is null");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdIsNotNull() {
            addCriterion("quetype_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdEqualTo(Short value) {
            addCriterion("quetype_id =", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdNotEqualTo(Short value) {
            addCriterion("quetype_id <>", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdGreaterThan(Short value) {
            addCriterion("quetype_id >", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdGreaterThanOrEqualTo(Short value) {
            addCriterion("quetype_id >=", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdLessThan(Short value) {
            addCriterion("quetype_id <", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdLessThanOrEqualTo(Short value) {
            addCriterion("quetype_id <=", value, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdIn(List<Short> values) {
            addCriterion("quetype_id in", values, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdNotIn(List<Short> values) {
            addCriterion("quetype_id not in", values, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdBetween(Short value1, Short value2) {
            addCriterion("quetype_id between", value1, value2, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andQuetypeIdNotBetween(Short value1, Short value2) {
            addCriterion("quetype_id not between", value1, value2, "quetypeId");
            return (Criteria) this;
        }

        public Criteria andChapterIdIsNull() {
            addCriterion("chapter_id is null");
            return (Criteria) this;
        }

        public Criteria andChapterIdIsNotNull() {
            addCriterion("chapter_id is not null");
            return (Criteria) this;
        }

        public Criteria andChapterIdEqualTo(Byte value) {
            addCriterion("chapter_id =", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdNotEqualTo(Byte value) {
            addCriterion("chapter_id <>", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdGreaterThan(Byte value) {
            addCriterion("chapter_id >", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdGreaterThanOrEqualTo(Byte value) {
            addCriterion("chapter_id >=", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdLessThan(Byte value) {
            addCriterion("chapter_id <", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdLessThanOrEqualTo(Byte value) {
            addCriterion("chapter_id <=", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdIn(List<Byte> values) {
            addCriterion("chapter_id in", values, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdNotIn(List<Byte> values) {
            addCriterion("chapter_id not in", values, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdBetween(Byte value1, Byte value2) {
            addCriterion("chapter_id between", value1, value2, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdNotBetween(Byte value1, Byte value2) {
            addCriterion("chapter_id not between", value1, value2, "chapterId");
            return (Criteria) this;
        }

        public Criteria andLevelIdIsNull() {
            addCriterion("level_id is null");
            return (Criteria) this;
        }

        public Criteria andLevelIdIsNotNull() {
            addCriterion("level_id is not null");
            return (Criteria) this;
        }

        public Criteria andLevelIdEqualTo(Byte value) {
            addCriterion("level_id =", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdNotEqualTo(Byte value) {
            addCriterion("level_id <>", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdGreaterThan(Byte value) {
            addCriterion("level_id >", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdGreaterThanOrEqualTo(Byte value) {
            addCriterion("level_id >=", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdLessThan(Byte value) {
            addCriterion("level_id <", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdLessThanOrEqualTo(Byte value) {
            addCriterion("level_id <=", value, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdIn(List<Byte> values) {
            addCriterion("level_id in", values, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdNotIn(List<Byte> values) {
            addCriterion("level_id not in", values, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdBetween(Byte value1, Byte value2) {
            addCriterion("level_id between", value1, value2, "levelId");
            return (Criteria) this;
        }

        public Criteria andLevelIdNotBetween(Byte value1, Byte value2) {
            addCriterion("level_id not between", value1, value2, "levelId");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswerIsNull() {
            addCriterion("subject_answer is null");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswerIsNotNull() {
            addCriterion("subject_answer is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswerEqualTo(String value) {
            addCriterion("subject_answer =", value, "subjectAnswer");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswerNotEqualTo(String value) {
            addCriterion("subject_answer <>", value, "subjectAnswer");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswerGreaterThan(String value) {
            addCriterion("subject_answer >", value, "subjectAnswer");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("subject_answer >=", value, "subjectAnswer");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswerLessThan(String value) {
            addCriterion("subject_answer <", value, "subjectAnswer");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswerLessThanOrEqualTo(String value) {
            addCriterion("subject_answer <=", value, "subjectAnswer");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswerLike(String value) {
            addCriterion("subject_answer like", value, "subjectAnswer");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswerNotLike(String value) {
            addCriterion("subject_answer not like", value, "subjectAnswer");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswerIn(List<String> values) {
            addCriterion("subject_answer in", values, "subjectAnswer");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswerNotIn(List<String> values) {
            addCriterion("subject_answer not in", values, "subjectAnswer");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswerBetween(String value1, String value2) {
            addCriterion("subject_answer between", value1, value2, "subjectAnswer");
            return (Criteria) this;
        }

        public Criteria andSubjectAnswerNotBetween(String value1, String value2) {
            addCriterion("subject_answer not between", value1, value2, "subjectAnswer");
            return (Criteria) this;
        }

        public Criteria andPpassportIdIsNull() {
            addCriterion("ppassport_id is null");
            return (Criteria) this;
        }

        public Criteria andPpassportIdIsNotNull() {
            addCriterion("ppassport_id is not null");
            return (Criteria) this;
        }

        public Criteria andPpassportIdEqualTo(Long value) {
            addCriterion("ppassport_id =", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdNotEqualTo(Long value) {
            addCriterion("ppassport_id <>", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdGreaterThan(Long value) {
            addCriterion("ppassport_id >", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ppassport_id >=", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdLessThan(Long value) {
            addCriterion("ppassport_id <", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdLessThanOrEqualTo(Long value) {
            addCriterion("ppassport_id <=", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdIn(List<Long> values) {
            addCriterion("ppassport_id in", values, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdNotIn(List<Long> values) {
            addCriterion("ppassport_id not in", values, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdBetween(Long value1, Long value2) {
            addCriterion("ppassport_id between", value1, value2, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdNotBetween(Long value1, Long value2) {
            addCriterion("ppassport_id not between", value1, value2, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeIsNull() {
            addCriterion("ppassport_time is null");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeIsNotNull() {
            addCriterion("ppassport_time is not null");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeEqualTo(Date value) {
            addCriterion("ppassport_time =", value, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeNotEqualTo(Date value) {
            addCriterion("ppassport_time <>", value, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeGreaterThan(Date value) {
            addCriterion("ppassport_time >", value, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ppassport_time >=", value, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeLessThan(Date value) {
            addCriterion("ppassport_time <", value, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeLessThanOrEqualTo(Date value) {
            addCriterion("ppassport_time <=", value, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeIn(List<Date> values) {
            addCriterion("ppassport_time in", values, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeNotIn(List<Date> values) {
            addCriterion("ppassport_time not in", values, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeBetween(Date value1, Date value2) {
            addCriterion("ppassport_time between", value1, value2, "ppassportTime");
            return (Criteria) this;
        }

        public Criteria andPpassportTimeNotBetween(Date value1, Date value2) {
            addCriterion("ppassport_time not between", value1, value2, "ppassportTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_subject
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 23 12:38:48 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_subject
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}