package sei.tk.service.dao.model;

import java.util.Date;

public class TkSubject {

    private Short testpaperScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_subject.subject_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_subject.course_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Short courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_subject.knopoint_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long knopointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_subject.quetype_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Short quetypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_subject.chapter_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Byte chapterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_subject.level_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Byte levelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_subject.subject_answer
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private String subjectAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_subject.ppassport_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long ppassportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_subject.ppassport_time
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Date ppassportTime;
    private String ppassportName;
    private String ppassportTimeString;

    
    public TkSubject() {
    }

    public TkSubject(Short courseId, Long knopointId, Short quetypeId) {
        this.courseId = courseId;
        this.knopointId = knopointId;
        this.quetypeId = quetypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_subject.subject_id
     *
     * @return the value of tk_subject.subject_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_subject.subject_id
     *
     * @param subjectId the value for tk_subject.subject_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_subject.course_id
     *
     * @return the value of tk_subject.course_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Short getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_subject.course_id
     *
     * @param courseId the value for tk_subject.course_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setCourseId(Short courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_subject.knopoint_id
     *
     * @return the value of tk_subject.knopoint_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getKnopointId() {
        return knopointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_subject.knopoint_id
     *
     * @param knopointId the value for tk_subject.knopoint_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setKnopointId(Long knopointId) {
        this.knopointId = knopointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_subject.quetype_id
     *
     * @return the value of tk_subject.quetype_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Short getQuetypeId() {
        return quetypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_subject.quetype_id
     *
     * @param quetypeId the value for tk_subject.quetype_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setQuetypeId(Short quetypeId) {
        this.quetypeId = quetypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_subject.chapter_id
     *
     * @return the value of tk_subject.chapter_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Byte getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_subject.chapter_id
     *
     * @param chapterId the value for tk_subject.chapter_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setChapterId(Byte chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_subject.level_id
     *
     * @return the value of tk_subject.level_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Byte getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_subject.level_id
     *
     * @param levelId the value for tk_subject.level_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setLevelId(Byte levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_subject.subject_answer
     *
     * @return the value of tk_subject.subject_answer
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public String getSubjectAnswer() {
        return subjectAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_subject.subject_answer
     *
     * @param subjectAnswer the value for tk_subject.subject_answer
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setSubjectAnswer(String subjectAnswer) {
        this.subjectAnswer = subjectAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_subject.ppassport_id
     *
     * @return the value of tk_subject.ppassport_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getPpassportId() {
        return ppassportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_subject.ppassport_id
     *
     * @param ppassportId the value for tk_subject.ppassport_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setPpassportId(Long ppassportId) {
        this.ppassportId = ppassportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_subject.ppassport_time
     *
     * @return the value of tk_subject.ppassport_time
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Date getPpassportTime() {
        return ppassportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_subject.ppassport_time
     *
     * @param ppassportTime the value for tk_subject.ppassport_time
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setPpassportTime(Date ppassportTime) {
        this.ppassportTime = ppassportTime;
    }

    public String getPpassportName() {
        return ppassportName;
    }

    public void setPpassportName(String ppassportName) {
        this.ppassportName = ppassportName;
    }

    public String getPpassportTimeString() {
        return ppassportTimeString;
    }

    public void setPpassportTimeString(String ppassportTimeString) {
        this.ppassportTimeString = ppassportTimeString;
    }

    public Short getTestpaperScore() {
        return testpaperScore;
    }

    public void setTestpaperScore(Short testpaperScore) {
        this.testpaperScore = testpaperScore;
    }
}