package sei.tk.service.dao.model;

import java.util.Date;

public class TkTestschedule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testschedule.testschedule_id
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    private Long testscheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testschedule.ppassport_id
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    private Long ppassportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testschedule.testpaper_id
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    private Long testpaperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testschedule.test_starttime
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    private Date testStarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testschedule.test_endtime
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    private Date testEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testschedule.course_id
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    private Short courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testschedule.stu_score
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    private Short stuScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testschedule.stu_basescore
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    private Short stuBasescore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testschedule.create_ppassport_id
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    private Long createPpassportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testschedule.create_time
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testschedule.testschedule_id
     *
     * @return the value of tk_testschedule.testschedule_id
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public Long getTestscheduleId() {
        return testscheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testschedule.testschedule_id
     *
     * @param testscheduleId the value for tk_testschedule.testschedule_id
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public void setTestscheduleId(Long testscheduleId) {
        this.testscheduleId = testscheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testschedule.ppassport_id
     *
     * @return the value of tk_testschedule.ppassport_id
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public Long getPpassportId() {
        return ppassportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testschedule.ppassport_id
     *
     * @param ppassportId the value for tk_testschedule.ppassport_id
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public void setPpassportId(Long ppassportId) {
        this.ppassportId = ppassportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testschedule.testpaper_id
     *
     * @return the value of tk_testschedule.testpaper_id
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public Long getTestpaperId() {
        return testpaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testschedule.testpaper_id
     *
     * @param testpaperId the value for tk_testschedule.testpaper_id
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public void setTestpaperId(Long testpaperId) {
        this.testpaperId = testpaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testschedule.test_starttime
     *
     * @return the value of tk_testschedule.test_starttime
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public Date getTestStarttime() {
        return testStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testschedule.test_starttime
     *
     * @param testStarttime the value for tk_testschedule.test_starttime
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public void setTestStarttime(Date testStarttime) {
        this.testStarttime = testStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testschedule.test_endtime
     *
     * @return the value of tk_testschedule.test_endtime
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public Date getTestEndtime() {
        return testEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testschedule.test_endtime
     *
     * @param testEndtime the value for tk_testschedule.test_endtime
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public void setTestEndtime(Date testEndtime) {
        this.testEndtime = testEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testschedule.course_id
     *
     * @return the value of tk_testschedule.course_id
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public Short getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testschedule.course_id
     *
     * @param courseId the value for tk_testschedule.course_id
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public void setCourseId(Short courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testschedule.stu_score
     *
     * @return the value of tk_testschedule.stu_score
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public Short getStuScore() {
        return stuScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testschedule.stu_score
     *
     * @param stuScore the value for tk_testschedule.stu_score
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public void setStuScore(Short stuScore) {
        this.stuScore = stuScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testschedule.stu_basescore
     *
     * @return the value of tk_testschedule.stu_basescore
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public Short getStuBasescore() {
        return stuBasescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testschedule.stu_basescore
     *
     * @param stuBasescore the value for tk_testschedule.stu_basescore
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public void setStuBasescore(Short stuBasescore) {
        this.stuBasescore = stuBasescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testschedule.create_ppassport_id
     *
     * @return the value of tk_testschedule.create_ppassport_id
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public Long getCreatePpassportId() {
        return createPpassportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testschedule.create_ppassport_id
     *
     * @param createPpassportId the value for tk_testschedule.create_ppassport_id
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public void setCreatePpassportId(Long createPpassportId) {
        this.createPpassportId = createPpassportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testschedule.create_time
     *
     * @return the value of tk_testschedule.create_time
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testschedule.create_time
     *
     * @param createTime the value for tk_testschedule.create_time
     *
     * @mbggenerated Fri Mar 25 12:43:32 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}