package sei.tk.service.dao.model;

public class TkTestanswer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testanswer.testpaperanswer_uuid
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long testpaperanswerUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testanswer.passport_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long passportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testanswer.testpaper_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long testpaperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testanswer.subject_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testanswer.subject_answer
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private String subjectAnswer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testanswer.testpaperanswer_uuid
     *
     * @return the value of tk_testanswer.testpaperanswer_uuid
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getTestpaperanswerUuid() {
        return testpaperanswerUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testanswer.testpaperanswer_uuid
     *
     * @param testpaperanswerUuid the value for tk_testanswer.testpaperanswer_uuid
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setTestpaperanswerUuid(Long testpaperanswerUuid) {
        this.testpaperanswerUuid = testpaperanswerUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testanswer.passport_id
     *
     * @return the value of tk_testanswer.passport_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getPassportId() {
        return passportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testanswer.passport_id
     *
     * @param passportId the value for tk_testanswer.passport_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setPassportId(Long passportId) {
        this.passportId = passportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testanswer.testpaper_id
     *
     * @return the value of tk_testanswer.testpaper_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getTestpaperId() {
        return testpaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testanswer.testpaper_id
     *
     * @param testpaperId the value for tk_testanswer.testpaper_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setTestpaperId(Long testpaperId) {
        this.testpaperId = testpaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testanswer.subject_id
     *
     * @return the value of tk_testanswer.subject_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testanswer.subject_id
     *
     * @param subjectId the value for tk_testanswer.subject_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testanswer.subject_answer
     *
     * @return the value of tk_testanswer.subject_answer
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public String getSubjectAnswer() {
        return subjectAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testanswer.subject_answer
     *
     * @param subjectAnswer the value for tk_testanswer.subject_answer
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setSubjectAnswer(String subjectAnswer) {
        this.subjectAnswer = subjectAnswer;
    }
}