package sei.tk.service.dao.model;

import java.util.ArrayList;
import java.util.List;

public class TkTeacherExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public TkTeacherExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTeacherIdIsNull() {
            addCriterion("teacher_id is null");
            return (Criteria) this;
        }

        public Criteria andTeacherIdIsNotNull() {
            addCriterion("teacher_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherIdEqualTo(String value) {
            addCriterion("teacher_id =", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotEqualTo(String value) {
            addCriterion("teacher_id <>", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdGreaterThan(String value) {
            addCriterion("teacher_id >", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_id >=", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdLessThan(String value) {
            addCriterion("teacher_id <", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdLessThanOrEqualTo(String value) {
            addCriterion("teacher_id <=", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdLike(String value) {
            addCriterion("teacher_id like", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotLike(String value) {
            addCriterion("teacher_id not like", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdIn(List<String> values) {
            addCriterion("teacher_id in", values, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotIn(List<String> values) {
            addCriterion("teacher_id not in", values, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdBetween(String value1, String value2) {
            addCriterion("teacher_id between", value1, value2, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotBetween(String value1, String value2) {
            addCriterion("teacher_id not between", value1, value2, "teacherId");
            return (Criteria) this;
        }

        public Criteria andPassportIdIsNull() {
            addCriterion("passport_id is null");
            return (Criteria) this;
        }

        public Criteria andPassportIdIsNotNull() {
            addCriterion("passport_id is not null");
            return (Criteria) this;
        }

        public Criteria andPassportIdEqualTo(Long value) {
            addCriterion("passport_id =", value, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdNotEqualTo(Long value) {
            addCriterion("passport_id <>", value, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdGreaterThan(Long value) {
            addCriterion("passport_id >", value, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdGreaterThanOrEqualTo(Long value) {
            addCriterion("passport_id >=", value, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdLessThan(Long value) {
            addCriterion("passport_id <", value, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdLessThanOrEqualTo(Long value) {
            addCriterion("passport_id <=", value, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdIn(List<Long> values) {
            addCriterion("passport_id in", values, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdNotIn(List<Long> values) {
            addCriterion("passport_id not in", values, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdBetween(Long value1, Long value2) {
            addCriterion("passport_id between", value1, value2, "passportId");
            return (Criteria) this;
        }

        public Criteria andPassportIdNotBetween(Long value1, Long value2) {
            addCriterion("passport_id not between", value1, value2, "passportId");
            return (Criteria) this;
        }

        public Criteria andTeaNameIsNull() {
            addCriterion("tea_name is null");
            return (Criteria) this;
        }

        public Criteria andTeaNameIsNotNull() {
            addCriterion("tea_name is not null");
            return (Criteria) this;
        }

        public Criteria andTeaNameEqualTo(String value) {
            addCriterion("tea_name =", value, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameNotEqualTo(String value) {
            addCriterion("tea_name <>", value, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameGreaterThan(String value) {
            addCriterion("tea_name >", value, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameGreaterThanOrEqualTo(String value) {
            addCriterion("tea_name >=", value, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameLessThan(String value) {
            addCriterion("tea_name <", value, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameLessThanOrEqualTo(String value) {
            addCriterion("tea_name <=", value, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameLike(String value) {
            addCriterion("tea_name like", value, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameNotLike(String value) {
            addCriterion("tea_name not like", value, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameIn(List<String> values) {
            addCriterion("tea_name in", values, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameNotIn(List<String> values) {
            addCriterion("tea_name not in", values, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameBetween(String value1, String value2) {
            addCriterion("tea_name between", value1, value2, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameNotBetween(String value1, String value2) {
            addCriterion("tea_name not between", value1, value2, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaGenderIsNull() {
            addCriterion("tea_gender is null");
            return (Criteria) this;
        }

        public Criteria andTeaGenderIsNotNull() {
            addCriterion("tea_gender is not null");
            return (Criteria) this;
        }

        public Criteria andTeaGenderEqualTo(String value) {
            addCriterion("tea_gender =", value, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderNotEqualTo(String value) {
            addCriterion("tea_gender <>", value, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderGreaterThan(String value) {
            addCriterion("tea_gender >", value, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderGreaterThanOrEqualTo(String value) {
            addCriterion("tea_gender >=", value, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderLessThan(String value) {
            addCriterion("tea_gender <", value, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderLessThanOrEqualTo(String value) {
            addCriterion("tea_gender <=", value, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderLike(String value) {
            addCriterion("tea_gender like", value, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderNotLike(String value) {
            addCriterion("tea_gender not like", value, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderIn(List<String> values) {
            addCriterion("tea_gender in", values, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderNotIn(List<String> values) {
            addCriterion("tea_gender not in", values, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderBetween(String value1, String value2) {
            addCriterion("tea_gender between", value1, value2, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderNotBetween(String value1, String value2) {
            addCriterion("tea_gender not between", value1, value2, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteIsNull() {
            addCriterion("tea_institute is null");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteIsNotNull() {
            addCriterion("tea_institute is not null");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteEqualTo(String value) {
            addCriterion("tea_institute =", value, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteNotEqualTo(String value) {
            addCriterion("tea_institute <>", value, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteGreaterThan(String value) {
            addCriterion("tea_institute >", value, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteGreaterThanOrEqualTo(String value) {
            addCriterion("tea_institute >=", value, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteLessThan(String value) {
            addCriterion("tea_institute <", value, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteLessThanOrEqualTo(String value) {
            addCriterion("tea_institute <=", value, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteLike(String value) {
            addCriterion("tea_institute like", value, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteNotLike(String value) {
            addCriterion("tea_institute not like", value, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteIn(List<String> values) {
            addCriterion("tea_institute in", values, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteNotIn(List<String> values) {
            addCriterion("tea_institute not in", values, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteBetween(String value1, String value2) {
            addCriterion("tea_institute between", value1, value2, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteNotBetween(String value1, String value2) {
            addCriterion("tea_institute not between", value1, value2, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaMajorIsNull() {
            addCriterion("tea_major is null");
            return (Criteria) this;
        }

        public Criteria andTeaMajorIsNotNull() {
            addCriterion("tea_major is not null");
            return (Criteria) this;
        }

        public Criteria andTeaMajorEqualTo(String value) {
            addCriterion("tea_major =", value, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorNotEqualTo(String value) {
            addCriterion("tea_major <>", value, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorGreaterThan(String value) {
            addCriterion("tea_major >", value, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorGreaterThanOrEqualTo(String value) {
            addCriterion("tea_major >=", value, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorLessThan(String value) {
            addCriterion("tea_major <", value, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorLessThanOrEqualTo(String value) {
            addCriterion("tea_major <=", value, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorLike(String value) {
            addCriterion("tea_major like", value, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorNotLike(String value) {
            addCriterion("tea_major not like", value, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorIn(List<String> values) {
            addCriterion("tea_major in", values, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorNotIn(List<String> values) {
            addCriterion("tea_major not in", values, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorBetween(String value1, String value2) {
            addCriterion("tea_major between", value1, value2, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorNotBetween(String value1, String value2) {
            addCriterion("tea_major not between", value1, value2, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaEmailIsNull() {
            addCriterion("tea_email is null");
            return (Criteria) this;
        }

        public Criteria andTeaEmailIsNotNull() {
            addCriterion("tea_email is not null");
            return (Criteria) this;
        }

        public Criteria andTeaEmailEqualTo(String value) {
            addCriterion("tea_email =", value, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailNotEqualTo(String value) {
            addCriterion("tea_email <>", value, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailGreaterThan(String value) {
            addCriterion("tea_email >", value, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailGreaterThanOrEqualTo(String value) {
            addCriterion("tea_email >=", value, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailLessThan(String value) {
            addCriterion("tea_email <", value, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailLessThanOrEqualTo(String value) {
            addCriterion("tea_email <=", value, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailLike(String value) {
            addCriterion("tea_email like", value, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailNotLike(String value) {
            addCriterion("tea_email not like", value, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailIn(List<String> values) {
            addCriterion("tea_email in", values, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailNotIn(List<String> values) {
            addCriterion("tea_email not in", values, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailBetween(String value1, String value2) {
            addCriterion("tea_email between", value1, value2, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailNotBetween(String value1, String value2) {
            addCriterion("tea_email not between", value1, value2, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaTelIsNull() {
            addCriterion("tea_tel is null");
            return (Criteria) this;
        }

        public Criteria andTeaTelIsNotNull() {
            addCriterion("tea_tel is not null");
            return (Criteria) this;
        }

        public Criteria andTeaTelEqualTo(String value) {
            addCriterion("tea_tel =", value, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelNotEqualTo(String value) {
            addCriterion("tea_tel <>", value, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelGreaterThan(String value) {
            addCriterion("tea_tel >", value, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelGreaterThanOrEqualTo(String value) {
            addCriterion("tea_tel >=", value, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelLessThan(String value) {
            addCriterion("tea_tel <", value, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelLessThanOrEqualTo(String value) {
            addCriterion("tea_tel <=", value, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelLike(String value) {
            addCriterion("tea_tel like", value, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelNotLike(String value) {
            addCriterion("tea_tel not like", value, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelIn(List<String> values) {
            addCriterion("tea_tel in", values, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelNotIn(List<String> values) {
            addCriterion("tea_tel not in", values, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelBetween(String value1, String value2) {
            addCriterion("tea_tel between", value1, value2, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelNotBetween(String value1, String value2) {
            addCriterion("tea_tel not between", value1, value2, "teaTel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_teacher
     *
     * @mbggenerated do_not_delete_during_merge Tue May 24 20:10:23 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_teacher
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}