package sei.tk.service.dao.model;

import java.util.Date;

public class TkTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_test.test_uuid
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long testUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_test.passport_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long passportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_test.testpaper_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long testpaperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_test.test_time
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Date testTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_test.test_ip
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private String testIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_test.test_uuid
     *
     * @return the value of tk_test.test_uuid
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getTestUuid() {
        return testUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_test.test_uuid
     *
     * @param testUuid the value for tk_test.test_uuid
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setTestUuid(Long testUuid) {
        this.testUuid = testUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_test.passport_id
     *
     * @return the value of tk_test.passport_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getPassportId() {
        return passportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_test.passport_id
     *
     * @param passportId the value for tk_test.passport_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setPassportId(Long passportId) {
        this.passportId = passportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_test.testpaper_id
     *
     * @return the value of tk_test.testpaper_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getTestpaperId() {
        return testpaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_test.testpaper_id
     *
     * @param testpaperId the value for tk_test.testpaper_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setTestpaperId(Long testpaperId) {
        this.testpaperId = testpaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_test.test_time
     *
     * @return the value of tk_test.test_time
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Date getTestTime() {
        return testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_test.test_time
     *
     * @param testTime the value for tk_test.test_time
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setTestTime(Date testTime) {
        this.testTime = testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_test.test_ip
     *
     * @return the value of tk_test.test_ip
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public String getTestIp() {
        return testIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_test.test_ip
     *
     * @param testIp the value for tk_test.test_ip
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setTestIp(String testIp) {
        this.testIp = testIp;
    }
}