package sei.tk.service.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TkTeacherExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_teacher
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_teacher
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tk_teacher
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public TkTeacherExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_teacher
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_teacher
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPpassportIdIsNull() {
            addCriterion("ppassport_id is null");
            return (Criteria) this;
        }

        public Criteria andPpassportIdIsNotNull() {
            addCriterion("ppassport_id is not null");
            return (Criteria) this;
        }

        public Criteria andPpassportIdEqualTo(Long value) {
            addCriterion("ppassport_id =", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdNotEqualTo(Long value) {
            addCriterion("ppassport_id <>", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdGreaterThan(Long value) {
            addCriterion("ppassport_id >", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ppassport_id >=", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdLessThan(Long value) {
            addCriterion("ppassport_id <", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdLessThanOrEqualTo(Long value) {
            addCriterion("ppassport_id <=", value, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdIn(List<Long> values) {
            addCriterion("ppassport_id in", values, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdNotIn(List<Long> values) {
            addCriterion("ppassport_id not in", values, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdBetween(Long value1, Long value2) {
            addCriterion("ppassport_id between", value1, value2, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andPpassportIdNotBetween(Long value1, Long value2) {
            addCriterion("ppassport_id not between", value1, value2, "ppassportId");
            return (Criteria) this;
        }

        public Criteria andTeaCodeIsNull() {
            addCriterion("tea_code is null");
            return (Criteria) this;
        }

        public Criteria andTeaCodeIsNotNull() {
            addCriterion("tea_code is not null");
            return (Criteria) this;
        }

        public Criteria andTeaCodeEqualTo(String value) {
            addCriterion("tea_code =", value, "teaCode");
            return (Criteria) this;
        }

        public Criteria andTeaCodeNotEqualTo(String value) {
            addCriterion("tea_code <>", value, "teaCode");
            return (Criteria) this;
        }

        public Criteria andTeaCodeGreaterThan(String value) {
            addCriterion("tea_code >", value, "teaCode");
            return (Criteria) this;
        }

        public Criteria andTeaCodeGreaterThanOrEqualTo(String value) {
            addCriterion("tea_code >=", value, "teaCode");
            return (Criteria) this;
        }

        public Criteria andTeaCodeLessThan(String value) {
            addCriterion("tea_code <", value, "teaCode");
            return (Criteria) this;
        }

        public Criteria andTeaCodeLessThanOrEqualTo(String value) {
            addCriterion("tea_code <=", value, "teaCode");
            return (Criteria) this;
        }

        public Criteria andTeaCodeLike(String value) {
            addCriterion("tea_code like", value, "teaCode");
            return (Criteria) this;
        }

        public Criteria andTeaCodeNotLike(String value) {
            addCriterion("tea_code not like", value, "teaCode");
            return (Criteria) this;
        }

        public Criteria andTeaCodeIn(List<String> values) {
            addCriterion("tea_code in", values, "teaCode");
            return (Criteria) this;
        }

        public Criteria andTeaCodeNotIn(List<String> values) {
            addCriterion("tea_code not in", values, "teaCode");
            return (Criteria) this;
        }

        public Criteria andTeaCodeBetween(String value1, String value2) {
            addCriterion("tea_code between", value1, value2, "teaCode");
            return (Criteria) this;
        }

        public Criteria andTeaCodeNotBetween(String value1, String value2) {
            addCriterion("tea_code not between", value1, value2, "teaCode");
            return (Criteria) this;
        }

        public Criteria andTeaNameIsNull() {
            addCriterion("tea_name is null");
            return (Criteria) this;
        }

        public Criteria andTeaNameIsNotNull() {
            addCriterion("tea_name is not null");
            return (Criteria) this;
        }

        public Criteria andTeaNameEqualTo(String value) {
            addCriterion("tea_name =", value, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameNotEqualTo(String value) {
            addCriterion("tea_name <>", value, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameGreaterThan(String value) {
            addCriterion("tea_name >", value, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameGreaterThanOrEqualTo(String value) {
            addCriterion("tea_name >=", value, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameLessThan(String value) {
            addCriterion("tea_name <", value, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameLessThanOrEqualTo(String value) {
            addCriterion("tea_name <=", value, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameLike(String value) {
            addCriterion("tea_name like", value, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameNotLike(String value) {
            addCriterion("tea_name not like", value, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameIn(List<String> values) {
            addCriterion("tea_name in", values, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameNotIn(List<String> values) {
            addCriterion("tea_name not in", values, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameBetween(String value1, String value2) {
            addCriterion("tea_name between", value1, value2, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaNameNotBetween(String value1, String value2) {
            addCriterion("tea_name not between", value1, value2, "teaName");
            return (Criteria) this;
        }

        public Criteria andTeaGenderIsNull() {
            addCriterion("tea_gender is null");
            return (Criteria) this;
        }

        public Criteria andTeaGenderIsNotNull() {
            addCriterion("tea_gender is not null");
            return (Criteria) this;
        }

        public Criteria andTeaGenderEqualTo(String value) {
            addCriterion("tea_gender =", value, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderNotEqualTo(String value) {
            addCriterion("tea_gender <>", value, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderGreaterThan(String value) {
            addCriterion("tea_gender >", value, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderGreaterThanOrEqualTo(String value) {
            addCriterion("tea_gender >=", value, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderLessThan(String value) {
            addCriterion("tea_gender <", value, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderLessThanOrEqualTo(String value) {
            addCriterion("tea_gender <=", value, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderLike(String value) {
            addCriterion("tea_gender like", value, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderNotLike(String value) {
            addCriterion("tea_gender not like", value, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderIn(List<String> values) {
            addCriterion("tea_gender in", values, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderNotIn(List<String> values) {
            addCriterion("tea_gender not in", values, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderBetween(String value1, String value2) {
            addCriterion("tea_gender between", value1, value2, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaGenderNotBetween(String value1, String value2) {
            addCriterion("tea_gender not between", value1, value2, "teaGender");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteIsNull() {
            addCriterion("tea_institute is null");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteIsNotNull() {
            addCriterion("tea_institute is not null");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteEqualTo(String value) {
            addCriterion("tea_institute =", value, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteNotEqualTo(String value) {
            addCriterion("tea_institute <>", value, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteGreaterThan(String value) {
            addCriterion("tea_institute >", value, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteGreaterThanOrEqualTo(String value) {
            addCriterion("tea_institute >=", value, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteLessThan(String value) {
            addCriterion("tea_institute <", value, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteLessThanOrEqualTo(String value) {
            addCriterion("tea_institute <=", value, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteLike(String value) {
            addCriterion("tea_institute like", value, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteNotLike(String value) {
            addCriterion("tea_institute not like", value, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteIn(List<String> values) {
            addCriterion("tea_institute in", values, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteNotIn(List<String> values) {
            addCriterion("tea_institute not in", values, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteBetween(String value1, String value2) {
            addCriterion("tea_institute between", value1, value2, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaInstituteNotBetween(String value1, String value2) {
            addCriterion("tea_institute not between", value1, value2, "teaInstitute");
            return (Criteria) this;
        }

        public Criteria andTeaMajorIsNull() {
            addCriterion("tea_major is null");
            return (Criteria) this;
        }

        public Criteria andTeaMajorIsNotNull() {
            addCriterion("tea_major is not null");
            return (Criteria) this;
        }

        public Criteria andTeaMajorEqualTo(String value) {
            addCriterion("tea_major =", value, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorNotEqualTo(String value) {
            addCriterion("tea_major <>", value, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorGreaterThan(String value) {
            addCriterion("tea_major >", value, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorGreaterThanOrEqualTo(String value) {
            addCriterion("tea_major >=", value, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorLessThan(String value) {
            addCriterion("tea_major <", value, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorLessThanOrEqualTo(String value) {
            addCriterion("tea_major <=", value, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorLike(String value) {
            addCriterion("tea_major like", value, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorNotLike(String value) {
            addCriterion("tea_major not like", value, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorIn(List<String> values) {
            addCriterion("tea_major in", values, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorNotIn(List<String> values) {
            addCriterion("tea_major not in", values, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorBetween(String value1, String value2) {
            addCriterion("tea_major between", value1, value2, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaMajorNotBetween(String value1, String value2) {
            addCriterion("tea_major not between", value1, value2, "teaMajor");
            return (Criteria) this;
        }

        public Criteria andTeaEmailIsNull() {
            addCriterion("tea_email is null");
            return (Criteria) this;
        }

        public Criteria andTeaEmailIsNotNull() {
            addCriterion("tea_email is not null");
            return (Criteria) this;
        }

        public Criteria andTeaEmailEqualTo(String value) {
            addCriterion("tea_email =", value, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailNotEqualTo(String value) {
            addCriterion("tea_email <>", value, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailGreaterThan(String value) {
            addCriterion("tea_email >", value, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailGreaterThanOrEqualTo(String value) {
            addCriterion("tea_email >=", value, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailLessThan(String value) {
            addCriterion("tea_email <", value, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailLessThanOrEqualTo(String value) {
            addCriterion("tea_email <=", value, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailLike(String value) {
            addCriterion("tea_email like", value, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailNotLike(String value) {
            addCriterion("tea_email not like", value, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailIn(List<String> values) {
            addCriterion("tea_email in", values, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailNotIn(List<String> values) {
            addCriterion("tea_email not in", values, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailBetween(String value1, String value2) {
            addCriterion("tea_email between", value1, value2, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaEmailNotBetween(String value1, String value2) {
            addCriterion("tea_email not between", value1, value2, "teaEmail");
            return (Criteria) this;
        }

        public Criteria andTeaTelIsNull() {
            addCriterion("tea_tel is null");
            return (Criteria) this;
        }

        public Criteria andTeaTelIsNotNull() {
            addCriterion("tea_tel is not null");
            return (Criteria) this;
        }

        public Criteria andTeaTelEqualTo(String value) {
            addCriterion("tea_tel =", value, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelNotEqualTo(String value) {
            addCriterion("tea_tel <>", value, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelGreaterThan(String value) {
            addCriterion("tea_tel >", value, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelGreaterThanOrEqualTo(String value) {
            addCriterion("tea_tel >=", value, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelLessThan(String value) {
            addCriterion("tea_tel <", value, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelLessThanOrEqualTo(String value) {
            addCriterion("tea_tel <=", value, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelLike(String value) {
            addCriterion("tea_tel like", value, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelNotLike(String value) {
            addCriterion("tea_tel not like", value, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelIn(List<String> values) {
            addCriterion("tea_tel in", values, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelNotIn(List<String> values) {
            addCriterion("tea_tel not in", values, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelBetween(String value1, String value2) {
            addCriterion("tea_tel between", value1, value2, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaTelNotBetween(String value1, String value2) {
            addCriterion("tea_tel not between", value1, value2, "teaTel");
            return (Criteria) this;
        }

        public Criteria andTeaPasswordIsNull() {
            addCriterion("tea_password is null");
            return (Criteria) this;
        }

        public Criteria andTeaPasswordIsNotNull() {
            addCriterion("tea_password is not null");
            return (Criteria) this;
        }

        public Criteria andTeaPasswordEqualTo(String value) {
            addCriterion("tea_password =", value, "teaPassword");
            return (Criteria) this;
        }

        public Criteria andTeaPasswordNotEqualTo(String value) {
            addCriterion("tea_password <>", value, "teaPassword");
            return (Criteria) this;
        }

        public Criteria andTeaPasswordGreaterThan(String value) {
            addCriterion("tea_password >", value, "teaPassword");
            return (Criteria) this;
        }

        public Criteria andTeaPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("tea_password >=", value, "teaPassword");
            return (Criteria) this;
        }

        public Criteria andTeaPasswordLessThan(String value) {
            addCriterion("tea_password <", value, "teaPassword");
            return (Criteria) this;
        }

        public Criteria andTeaPasswordLessThanOrEqualTo(String value) {
            addCriterion("tea_password <=", value, "teaPassword");
            return (Criteria) this;
        }

        public Criteria andTeaPasswordLike(String value) {
            addCriterion("tea_password like", value, "teaPassword");
            return (Criteria) this;
        }

        public Criteria andTeaPasswordNotLike(String value) {
            addCriterion("tea_password not like", value, "teaPassword");
            return (Criteria) this;
        }

        public Criteria andTeaPasswordIn(List<String> values) {
            addCriterion("tea_password in", values, "teaPassword");
            return (Criteria) this;
        }

        public Criteria andTeaPasswordNotIn(List<String> values) {
            addCriterion("tea_password not in", values, "teaPassword");
            return (Criteria) this;
        }

        public Criteria andTeaPasswordBetween(String value1, String value2) {
            addCriterion("tea_password between", value1, value2, "teaPassword");
            return (Criteria) this;
        }

        public Criteria andTeaPasswordNotBetween(String value1, String value2) {
            addCriterion("tea_password not between", value1, value2, "teaPassword");
            return (Criteria) this;
        }

        public Criteria andTeaCreatetimeIsNull() {
            addCriterion("tea_createtime is null");
            return (Criteria) this;
        }

        public Criteria andTeaCreatetimeIsNotNull() {
            addCriterion("tea_createtime is not null");
            return (Criteria) this;
        }

        public Criteria andTeaCreatetimeEqualTo(Date value) {
            addCriterion("tea_createtime =", value, "teaCreatetime");
            return (Criteria) this;
        }

        public Criteria andTeaCreatetimeNotEqualTo(Date value) {
            addCriterion("tea_createtime <>", value, "teaCreatetime");
            return (Criteria) this;
        }

        public Criteria andTeaCreatetimeGreaterThan(Date value) {
            addCriterion("tea_createtime >", value, "teaCreatetime");
            return (Criteria) this;
        }

        public Criteria andTeaCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("tea_createtime >=", value, "teaCreatetime");
            return (Criteria) this;
        }

        public Criteria andTeaCreatetimeLessThan(Date value) {
            addCriterion("tea_createtime <", value, "teaCreatetime");
            return (Criteria) this;
        }

        public Criteria andTeaCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("tea_createtime <=", value, "teaCreatetime");
            return (Criteria) this;
        }

        public Criteria andTeaCreatetimeIn(List<Date> values) {
            addCriterion("tea_createtime in", values, "teaCreatetime");
            return (Criteria) this;
        }

        public Criteria andTeaCreatetimeNotIn(List<Date> values) {
            addCriterion("tea_createtime not in", values, "teaCreatetime");
            return (Criteria) this;
        }

        public Criteria andTeaCreatetimeBetween(Date value1, Date value2) {
            addCriterion("tea_createtime between", value1, value2, "teaCreatetime");
            return (Criteria) this;
        }

        public Criteria andTeaCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("tea_createtime not between", value1, value2, "teaCreatetime");
            return (Criteria) this;
        }

        public Criteria andTeaIsonlineIsNull() {
            addCriterion("tea_isonline is null");
            return (Criteria) this;
        }

        public Criteria andTeaIsonlineIsNotNull() {
            addCriterion("tea_isonline is not null");
            return (Criteria) this;
        }

        public Criteria andTeaIsonlineEqualTo(Boolean value) {
            addCriterion("tea_isonline =", value, "teaIsonline");
            return (Criteria) this;
        }

        public Criteria andTeaIsonlineNotEqualTo(Boolean value) {
            addCriterion("tea_isonline <>", value, "teaIsonline");
            return (Criteria) this;
        }

        public Criteria andTeaIsonlineGreaterThan(Boolean value) {
            addCriterion("tea_isonline >", value, "teaIsonline");
            return (Criteria) this;
        }

        public Criteria andTeaIsonlineGreaterThanOrEqualTo(Boolean value) {
            addCriterion("tea_isonline >=", value, "teaIsonline");
            return (Criteria) this;
        }

        public Criteria andTeaIsonlineLessThan(Boolean value) {
            addCriterion("tea_isonline <", value, "teaIsonline");
            return (Criteria) this;
        }

        public Criteria andTeaIsonlineLessThanOrEqualTo(Boolean value) {
            addCriterion("tea_isonline <=", value, "teaIsonline");
            return (Criteria) this;
        }

        public Criteria andTeaIsonlineIn(List<Boolean> values) {
            addCriterion("tea_isonline in", values, "teaIsonline");
            return (Criteria) this;
        }

        public Criteria andTeaIsonlineNotIn(List<Boolean> values) {
            addCriterion("tea_isonline not in", values, "teaIsonline");
            return (Criteria) this;
        }

        public Criteria andTeaIsonlineBetween(Boolean value1, Boolean value2) {
            addCriterion("tea_isonline between", value1, value2, "teaIsonline");
            return (Criteria) this;
        }

        public Criteria andTeaIsonlineNotBetween(Boolean value1, Boolean value2) {
            addCriterion("tea_isonline not between", value1, value2, "teaIsonline");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_teacher
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 25 17:28:35 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tk_teacher
     *
     * @mbggenerated Fri Mar 25 17:28:35 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}