package sei.tk.service.dao.model;

public class TkTeacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_teacher.teacher_id
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    private String teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_teacher.passport_id
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    private Long passportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_teacher.tea_name
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    private String teaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_teacher.tea_gender
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    private String teaGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_teacher.tea_institute
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    private String teaInstitute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_teacher.tea_major
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    private String teaMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_teacher.tea_email
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    private String teaEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_teacher.tea_tel
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    private String teaTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_teacher.teacher_id
     *
     * @return the value of tk_teacher.teacher_id
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_teacher.teacher_id
     *
     * @param teacherId the value for tk_teacher.teacher_id
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_teacher.passport_id
     *
     * @return the value of tk_teacher.passport_id
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public Long getPassportId() {
        return passportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_teacher.passport_id
     *
     * @param passportId the value for tk_teacher.passport_id
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setPassportId(Long passportId) {
        this.passportId = passportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_teacher.tea_name
     *
     * @return the value of tk_teacher.tea_name
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public String getTeaName() {
        return teaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_teacher.tea_name
     *
     * @param teaName the value for tk_teacher.tea_name
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setTeaName(String teaName) {
        this.teaName = teaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_teacher.tea_gender
     *
     * @return the value of tk_teacher.tea_gender
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public String getTeaGender() {
        return teaGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_teacher.tea_gender
     *
     * @param teaGender the value for tk_teacher.tea_gender
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setTeaGender(String teaGender) {
        this.teaGender = teaGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_teacher.tea_institute
     *
     * @return the value of tk_teacher.tea_institute
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public String getTeaInstitute() {
        return teaInstitute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_teacher.tea_institute
     *
     * @param teaInstitute the value for tk_teacher.tea_institute
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setTeaInstitute(String teaInstitute) {
        this.teaInstitute = teaInstitute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_teacher.tea_major
     *
     * @return the value of tk_teacher.tea_major
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public String getTeaMajor() {
        return teaMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_teacher.tea_major
     *
     * @param teaMajor the value for tk_teacher.tea_major
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setTeaMajor(String teaMajor) {
        this.teaMajor = teaMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_teacher.tea_email
     *
     * @return the value of tk_teacher.tea_email
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public String getTeaEmail() {
        return teaEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_teacher.tea_email
     *
     * @param teaEmail the value for tk_teacher.tea_email
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setTeaEmail(String teaEmail) {
        this.teaEmail = teaEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_teacher.tea_tel
     *
     * @return the value of tk_teacher.tea_tel
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public String getTeaTel() {
        return teaTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_teacher.tea_tel
     *
     * @param teaTel the value for tk_teacher.tea_tel
     *
     * @mbggenerated Tue May 24 20:10:23 CST 2016
     */
    public void setTeaTel(String teaTel) {
        this.teaTel = teaTel;
    }
}