package sei.tk.service.dao.model;

public class TkTestsubject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testsubject.testpaper_uuid
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long testpaperUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testsubject.testpaper_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long testpaperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testsubject.subject_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Long subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_testsubject.testpaper_score
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    private Short testpaperScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testsubject.testpaper_uuid
     *
     * @return the value of tk_testsubject.testpaper_uuid
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getTestpaperUuid() {
        return testpaperUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testsubject.testpaper_uuid
     *
     * @param testpaperUuid the value for tk_testsubject.testpaper_uuid
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setTestpaperUuid(Long testpaperUuid) {
        this.testpaperUuid = testpaperUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testsubject.testpaper_id
     *
     * @return the value of tk_testsubject.testpaper_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getTestpaperId() {
        return testpaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testsubject.testpaper_id
     *
     * @param testpaperId the value for tk_testsubject.testpaper_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setTestpaperId(Long testpaperId) {
        this.testpaperId = testpaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testsubject.subject_id
     *
     * @return the value of tk_testsubject.subject_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testsubject.subject_id
     *
     * @param subjectId the value for tk_testsubject.subject_id
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_testsubject.testpaper_score
     *
     * @return the value of tk_testsubject.testpaper_score
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public Short getTestpaperScore() {
        return testpaperScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_testsubject.testpaper_score
     *
     * @param testpaperScore the value for tk_testsubject.testpaper_score
     *
     * @mbggenerated Wed Mar 23 12:38:48 CST 2016
     */
    public void setTestpaperScore(Short testpaperScore) {
        this.testpaperScore = testpaperScore;
    }
}